#!/bin/sh

enviamensaje () {

	/usr/lib/sendmail -f jjamor@hispalinux.es $1 <<FINM
From: Juan Jose Amor <jjamor@hispalinux.es>
To: $1
Subject: Acerca de la suscripcion de LuCAS

	Hola,

	Perdona este último mensaje (es ya el último, lo prometo :-) )

	Por una caida del servidor y otros errores acumulados, se ha emitido
hace un rato un mensaje advirtiendo de que seguías desuscrito.

	Si ya diste orden a lucas-request@hispalinux.es de que querías
resuscribirte no es necesario que lo hagas de nuevo.

	Ah, y el mensaje *no* se va a repetir en una semana ;-)

	Disculpa las molestias.

	Saludos, Juanjo AI
	Administración de la lista LuCAS


--

  Juan Jose Amor Iglesias         E-Mail: jjamor@hispalinux.es
  Asoc. HispaLiNUX              PGP Key ID: 75C9B305 available

FINM

}


if [ ! -f lista-desuscritos ];
then
	echo "Error: no existe el fichero lista-desuscritos"
	exit 1
fi

for PERSONA in `cat lista-desuscritos`
do
	enviamensaje $PERSONA
	sleep 5
done

exit 0

