#!/bin/sh
#ps2gif script by Ian Hutchinson 1997; use at your own risk.
#You need Ghostscript and the pbmplus utilities installed. 
if [ $# != 2 ] ; then
       echo " Usage: $0 <file.ps> <file.gif>" 1>&2
       exit 1
else 
	echo "Calling ghostscript to convert, please wait ..." >&2
	gs -sDEVICE=ppm -sOutputFile=- -sNOPAUSE -q $1 -c showpage -c quit | pnmcrop| pnmmargin 10 | ppmtogif >$2
fi


