#!/bin/bash

ARCHIVOS="ADFONTS.MFM
ADOBEPS4.DRV
ADOBEPS4.HLP
DEFPRTR2.PPD
ICONLIB.DLL
PSMON.DLL
ADOBEPS5.DLL
ADOBEPSU.DLL
ADOBEPSU.HLP"

for x in $ARCHIVOS
do
        find `pwd` -name "$x" -exec /bin/cp -vf {} /usr/share/cups/drivers \;
done

chmod -v 644 /usr/share/cups/drivers/*
