./. groff -man -Tascii imprenta-e.1
.TH IMPRENTA-E 1 
.SH NAME
imprenta-e - sistema automatizado de publicacion de documentos
.SH SYNOPSIS
imprenta-e
.SH DESCRIPTION
.B imprenta-e
La imprenta-e es una aplicacion que pretende estructurar y
automatizar las tareas de publicacion de documentos en sitios web.
Primero obtiene las fuentes del documento (DocBook SGML, DocBook
XML y Linuxdoc) de un repositorio CVS. Luego comprueba la existencia
del documento y comprueba las versiones; hace las actualizaciones
necesarias. Si no existe instala su ficha en formato omf en
~share/imprenta-e/omf.

Crea los formatos de publicacion especificados(ps, pdf,	html
y html-comprimido) asi como empaqueta los fuentes para su
distribucion almacenandolos en un directorio. Crea el index.html
y copia el directorio que contiene los fichers de publicacion
al destino especificado. Luego crea una entrada en el archivo RSS
correspondiente a los agregadoes web.
.SH CONFIGURACION

La configuracion se divide en X archivos diferentes:

.I /etc/imprenta-e/imprenta-e.conf
que determina el origen de los fuentes y el destino de los formatos de publicacion.

.I /etc/imprenta-e/server.conff
que determina los diferentes web alojados en un servidor y cuales deben ser atendidos

.SH /etc/imprenta-e/imprenta-e.conf

Este archivo es el encargado de informar a la 
.B imprenta-e
del origen de los fuentes, los formatos a crear y el destino de estos en el servidor

Un fichero de ejemplo esta disponible en 
.I ejemplos/conf/imprenta-e.conf
en el directorio donde se descomprimio el codigo fuente de la
-B imprenta-e

Este archivo traqta cada documento como un modulo de un repositorio CVS. El atributo origen del modulo en estos momentos solo puede contener el valor CVS.

Elementos de
.B modulo

.B CVSROOT
 - es el repositorio CVS al que pertenece el modulo

.B nombre_modulo
 - es el nombre del modul a descargar

.B aop
 - es el nombre del archivo AOP (Archivo de Opciones de Procesamiento)

.B destino
 - es el directorio con los formatos de publicacion que ha crado la imprenta-e, es decir la ruta real donde se copiara.

.B formatos
 - son los formatos a crear. Toma como argumentos ps, pdf, htmltgz y html. A su vez cada argumento toma un valor si o no, que indica si debe generarse dicho formato o no. El argumento htmltgz genera un directorio con los html y un tgz con los html, mientras que html genera los html en el directorio raiz, es recomendable para cuando el documento esta disponible solo online.

.B web
 - contiene un identificador del web donde se alojara la documentacion. Esta etiqueta fue incluida debido a la posibilidad de que en un mismo servidor se albergue mas de un sitio web que contenga documetnacion. Ademas es una forma de relacionar un web con su propia configuracion que estara especificada en el archivo
.I server.conf

.SH /etc/imprenta-e/server.conf

Este archivo es el encargado de informar a la
.B imprenta-e
de los diferentes web que estan alojados en el servidor y a los que esta debe atender

Un fichero de ejemplo esta disponible en
.I ejemplos/conf/server.conf
en el directorio donde se descomprimio el codigo fuente de la 
.B imprenta-e

En este archivo cada etiqueta 
.I <item>
de corresponde con un web alojado en el servidor. Los diferentes atributos proporcionan informacion necesaria para los diferentes archivos que creara la 
.B imprenta-e

.B id
 - identificador que facilita el acceso a la informacion relativa a un web concreto. Relaciona el modulo con la web al que pertenece. Se corresponde al atributo del elemento 
.I <web>
del archivo
.I imprenta-e.conf

.B type
 - el tipo de documento. Este atributo puede tomar valores como manua, desarrollo, usuario, tutoria, etc.

La
.B imprenta-e
cra un fichero
.I RDF
para cada tipo de documento. El fichero contiene el nombre del tipo de documento.

Si en un mismo web hay mas de un tipo debe crearse una entrada en el archivo por cada tipo de documento, donde el atributo
.I id
es el mismo.

.B title
 - Titulo para el
.I RDF

.B descriptor
 - pequeña descripcion del contenido del
.I RDF

.B url_index_doc
 - URL al indice de la documentacion

.B url_doc
 - URL al directorio que contiene la documentacion creada por la
.B imprenta-e

.B stylesheet
 - nombre de la hoja de estilo a aplicar para crar el
.I index.html
de cada documento

.SH CONFIGURACION DE CADA DOCUMENTO

Estos archivos deben acompañar a cada documento, por lo que deben estar presentes en cada modulo deel CVS. Son dos lo archivos:
.B AOP
y
.B OMF

.SH Archivos AOP

Los
.B Archivos de Opciones de Procesamiento
son los archivos que contienen los parametros a pasar al
.B impresor-e

Un fichero de ejemplo esta disponible en 
.I ejemplos/aop/ejemplo.aop
en el directorio donde se descomprimio el codigo fuente de la
.B imprenta-e

El objetivo de este archivo es informar al
.B impresor-e
de las caracteristicas del documento, es decir si el documento contiene imagenes, si estan en un directorio aparte o junto a los fuentes, el nombre del archivo principal asi como el nombre del directorio que creara la imprenta-e para contener los diferentes formatos.

.B formato_fuente tipo=<tipo>
 - Formato del documento tipo: DocBook, DocBookXML y Linuxdoc.

.B nombre_base
 - nombre del directorio que creara la
.B imprenta-e
para contener los diferentes formatos

.B nombre_archivo
 - nombre del archivo principal del documento, si este contiene, y su ubicacion

.B imagenes
 - contiene toma valores si | no y nombre_directorio contiene la ubicacion de las imagenes.

.B ejemplos
 - contiene toma valores si | no y nombre_directorio la ubicacion de los ejemplos. (siempre deben estar en un directorio)

.SH Archivos OMF

El archivo
.B OMF
proporciona una descripcion del documento, asi como la vesion y la fecha.

Un fichero de ejemplo esta disponible en
.I ejemplos/omf/ejemplo.omf
en el directorio donde se descomprimio el codigo fuetne de la
.B imprenta-e

La
.B imprenta-e
utiliza los datos de este archivo de dos maneras. En primer lugar extrae los datos del autor, titulo del documento, version, fecha y descripcion para crear el 
.I index.html
del documento. En segundo lugar comprueba la existencia del documento y si es necesario actualizarlo. Para ello este archivo se copia a 
.I /share/imprenta-e/omf

.SH El editor-e

Ya que estos archivos son necesarios para cada documento, se ha creado un formulario web que crea de forma automatica el esqueleto de un documento y lo envia por correo electroinico a la direccion especificada.

Podes crear vuestros proyectos de documentacion desde
.I http://www.es.gnome.org/documentacion/editor/index.php

.SH Hojas de estilo

Para crear el archivo
.I index.html
de cada documento la 
.B imprenta-e
crea un archivo
.I index.xml
sobre el que aplica la hoja de estilo XSL indicada en el archivo de configuracion
.I server.conf
y que debe encontrarse en
.I /share/imprenta-e/XSLT

La DTD del archivo
.I index.xml
esta disponible en
.I ejemplos/dtd/index-doc.dtd

.SH EJEMPLOS

los ejemplos estan disponibles en el directorio del codigo fuente de la imprenta-e o en el CVS de hispalinux via web
.I http://cvs.hispalinux.es/cgi-bin/cvs-web/rl-imprenta-e/ejemplos

.SH NOTAS

crear el archivo de ejemplo ~/ejemplos/aop/ejemplo.aop

.SH AUTOR

Gaspar Oriol (gaspar.oriol@hispalinux.es)

.SH BUGS

Reportar los bugs mediante el bugzilla de hispalinus
.I bugzilla.hispalinux.es