\input texinfo  @c -*-texinfo-*-
@comment Documentation for CVS.
@comment This document is free software; you can redistribute and/or modify
@comment it under the terms of the GNU General Public License as published by
@comment the Free Software Foundation; either version 2, or (at your option)
@comment any later version.

@comment This document is distributed in the hope that it will be useful,
@comment but WITHOUT ANY WARRANTY; without even the implied warranty of
@comment MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@comment GNU General Public License for more details.

@comment Este fichero ha sido traducido por
@comment Carlos García Recio <carlosgrecio@@eresmas.com>
@comment  
@comment Se ceden todos los derechos bajo la licencia de documentación de 
@comment la GNU (fdl) que se puede encontrar en http://www.gnu.org/

 
@finalout

@setfilename cvsbook.info
@settitle Desarrollo de Código Abierto con CVS
@setchapternewpage odd

@c Prefiero que los párrafos se ajusten a la izquierda cuado la fuente
@c es de ancho fijo, especialmente cuando los párrafos están
@c intercalados con ejemplos de código identado, lo que ocurre con
@c frecuencia en el documento.
@ifnottex
@paragraphindent 0
@end ifnottex

@c Se pierden los valores por defecto del navegador. Ponemos texto
@c negro en fondo blanco.
@ifhtml
@html
<body bgcolor="#FFFFFF" fgcolor="#000000">
@end html
@end ifhtml

@ifinfo
@format
START-INFO-DIR-ENTRY
* El libro de CVS: (cvsbook).           Un tutorial de CVS y referencia.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@ifnottex
Copyright @copyright{} 1999, 2000 Karl Fogel <kfogel@@red-bean.com>
  
This document is free software; you can redistribute and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

This document is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
@end ifnottex

@comment La sección titlepage no aparece en el el fichero Info
@titlepage
@sp 4
@comment El título se imprime en una fuente grande
@center @titlefont{Desarrollo de Código Abierto}
@sp
@center @titlefont{Con}
@sp
@center @titlefont{CVS}
@comment -release-
@sp 3
@center Karl Fogel <kfogel@@red-bean.com>

@comment  Los siguientes dos comandos comienzan la página de copyright
@comment  para el manual impreso. Esto no aparece en el fichero Info.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999, 2000 Karl Fogel <kfogel@@red-bean.com>

This document is free software; you can redistribute and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

This document is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
@end titlepage

@comment ================================================================
@comment                   El texto real comienza aqui
@comment ================================================================

@include version.texi

Este manual describe como usar y administrar CVS (Concurrent Versions
System). Es parte un trabajo mayor titulado @cite{Desarrollo de Código
Abierto con CVS}; por favor, lea la introducción para más detalles.

Esta es la versión @value{VERSION} de este manual.

@summarycontents
@contents

@ifnottex
@c ---------------------------------------------------------------------
@node Top
@top
@unnumbered Top

@menu
* Introduccion::                        ¿Que es este libro?
* Una introduccion a CVS::              Uso básico de CVS  -- un tutorial.
* Administracion del Repositorio::      Como manejar el repositorio de CVS.
* CVS avanzado::                        Lo que saben los gurús.
* Problemas y Soluciones::              FAQs y experiencias de la vida real.
* Referencia de CVS::                   Una referencia de los comandos de CVS, variables, etc.
* Herramientas de terceros::            Otras herramientas que trabajan con CVS.
* Índice::
* GNU General Public License::
* GNU Free Documentation License::
@end menu
@end ifnottex

@c ----------------------------------------------------------------------

@c Chapters 1, 3, 5, and 7 don't exist.  See introduction for why.

@include introduction.texi
@include chapter-2.texi
@include chapter-4.texi
@include chapter-6.texi
@include chapter-8.texi
@include chapter-9.texi
@include chapter-10.texi
@include index.texi
@include gpl.texi
@include fdl.texi

@c ----------------------------------------------------------------------

@bye
