.\"
.\" Translated 20 Jul 1998 by Juan José López Mellado (laveneno@hotmail.com)
.\"
.TH ANSI2KNR 1 "31 Diciembre 1990" 
.SH NOMBRE
ansi2knr \- convierte de C tipo ANSI a C tipo Kernighan & Ritchie
.SH SINOPSIS
.I ansi2knr
input_file output_file
.SH DESCRIPCIÓN
Si no se especifica fichero de salida (output_file), la salida va a
parar a la salida estándar (stdout).
.br
No hay mensajes de error.
.sp
.I ansi2knr
reconoce las funciones buscando algún nombre que no sea identificador en el
margen izquierdo, seguido por un paréntesis izquierdo, con un paréntesis
derecho como último carácter de la linea. Reconocerá una cabecera multilinea
si el último carácter de cada linea menos la ultima es un paréntesis
izquierdo o una coma. Estos algoritmos ignoran los espacios en blanco y
los comentarios, excepto que el nombre de la función debe ser el primer
elemento de la linea.
.sp
Las construcciones siguientes confundirán a estos algoritmos:
.br
     - Cualquier otra construcción que comience en el margen izquierdo y
siga la sintaxis explicada arriba (como una macro o una llamada a función).
.br
     - Macros que trabajen con la sintaxis de la cabecera de la función.
