.\" Translated Jul 28 1998 by Román Ramírez <rramirez@encomix.es>
.\" arch.1 -- 
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Copyright 1998 Translation Roman Ramirez (patowc@encomix.es)
.\" Public domain: may be freely distributed.
.\"
.TH ARCH 1 "4 Julio 1997" "Linux 2.0" "Manual del Programador de Linux"
.SH NOMBRE
arch \- muestra la arquitectura de la máquina
.SH SINOPSIS
.B arch
.SH DESCRIPCIÓN
.B arch
is equivalente a
.BR "uname -m" .

En los sistemas Linux actuales,
.B arch
imprime cosas como  "i386", "i486", "i586", "alpha", "sparc",
"arm", "m68k", "mips", "ppc".
.SH VÉASE TAMBIÉN
.BR uname "(1), " uname (2)
.\"
.\" Detalles:
.\" arch imprime la parte de la máquina de la estructura system_utsname
.\" Esta estructura está definida en version.c, y este campo se
.\" inicializa con UTS_MACHINE, el cual está definido en $ARCH
.\" en el Makefile principal.
.\" Eso da las posibilidades 
.\" alpha    arm      i386     m68k     mips     ppc      sparc    sparc64
.\"
.\" Si el Makefile no es editado, ARCH se averigua a través de
.\" ARCH := $(shell uname -m | sed -e s/i.86/i386/ -e s/sun4u/sparc64/)
.\" Entonves, ¿cómo obtenemos eso valored de i586?
.\" Bien, la rutina check_bugs() hace system_utsname.machine[1] = '0' + x86;
.\" (llamada en init/main.c, definida en ./include/asm-i386/bugs.h)
