.\" -*- nroff -*-
.\"Traducida por Pedro Pablo Fábrega, Julio 98 <pfabrega@arrakis.es>"
.TH BASENAME 1 "Utilidades Shell GNU" "FSF"
.SH NOMBRE
basename \- elimina directorios y sufijos de los nombres de ficheros
.SH SINOPSIS
.B basename
nombre [sufijo]
.br
.B basename
{\-\-help,\-\-version}
.SH DESCRIPCIÓN
Esta documentación no será mantenida y puede ser inexacta o incompleta.
La documentación Texinfo es ahora la fuente autorizada.
.PP
Esta página de manual documenta la versión GNU de 
.BR basename.
El comando
.B basename
elimina cualquier componente directorio de 
.IR name ;
Si se especifica
.I sufijo
y es idéntico al final de 
.IR nombre ,
se ellimina de 
.I nombre
también .
.B basename
imprime el nombre  resultante en la salida estándar.
.SS OPCIONES
.TP
.I "\-\-help"
Imprime un mensaje de uso en la salida estándar y termina correctamente.
.TP
.I "\-\-version"
Imprime información sobre la versión en la salida estándar y termina
correctamente.
