.\" -*- nroff -*-
.\"Traducida por Pedro Pablo Fábrega, Julio 98 <pfabrega@arrakis.es>"
.TH CHROOT 1L "Utilidades Shell GNU" "FSF"
.SH NOMBRE
chroot \- ejecuta comandos o shells interactivos con un directorio raíz
especial.
.SH SINOPSIS
.B chroot
[\-\-help] [\-\-version]
directorio [command...]
.SH DESCRIPCIÓN
Esta documentación no será mantenida y puede ser inexacta o incompleta.
La documentación Texinfo es ahora la fuente autorizada.
.PP
Esta página de manual documenta la versión GNU de
.BR chroot .
.B chroot
ejecuta un comando con un directorio específico como directorio raíz
para la traducción de nombres de ficheros.
Si no especificamos comando
.B chroot
ejecuta una shell interactiva. La variable de entorno `SHELL' especifica el
programa shell; por defecto es /bin/sh.
.SS OPCIONES
.I "\-\-help"
Imprime un mensaje de uso en la salida estándar y termina correctamente.
.TP
.I "\-\-version"
Imprime información sobre la versión en la salida estándar y termina
correctamente.
.SS NOTAS
En muchos sistemas sólo el superusuario puede cambiar el directorio raíz.
