.\" @(#)chvt.1 1.0 970126 aeb
.\"
.\" Translated into Spanish on Thu Dec 3 1998 by Gerardo Aburruzaga
.\" García <gerardo.aburruzaga@uca.es>
.\"
.TH CHVT 1 "26 de Enero de 1997"
.SH NOMBRE
chvt \- cambia la terminal virtual en primer plano
.SH SINOPSIS
.B chvt
.I N
.SH DESCRIPCIÓN
La orden
.B chvt
.I N
hace que
.I /dev/ttyN
sea la terminal en uso.
(La pantalla correspondiente se crea si no existía aún.
Para deshacerse de VTs que no se usan,
emplee
.BR deallocvt (1).)
La combinación de teclas (Ctrl-)AltIzda-F<N> (con <N> en el rango 1-12)
tiene usualmente un efecto similar.

