.\" @(#)deallocvt.1 1.0 970317 aeb
.\"
.\" Translated into Spanish on Thu Dec 3 1998 by Gerardo Aburruzaga
.\" García <gerardo.aburruzaga@uca.es>
.\"
.TH DEALLOCVT 1 "17 de Marzo de 1997"
.SH NOMBRE
deallocvt \- desasigna consolas virtuales en desuso
.SH SINOPSIS
.B deallocvt
[
.I N
]
.SH DESCRIPCIÓN
.LP
El programa
.B deallocvt
libera memoria y estructuras de datos del núcleo para todas las
consolas virtuales que no se usen.
Si se da un argumento
.IR N ,
solamente se desasigna
.IR /dev/ttyN .

Una consola virtual se considera en desuso si no es la consola en
primer plano, ni ningún proceso la tiene abierta para lectura o
escritura, ni se ha seleccionado ningún texto en su pantalla.
.SH "VÉASE TAMBIÉN"
.BR chvt (1),
.BR openvt (1)
