.\" -*- nroff -*-
.\" Traslated 24 Aug 1998 Victor Moral (victor@venexma.es)
.\"
.TH ECHO 1 "Utilidades shell de GNU" "FSF"
.SH NOMBRE
echo \- muestra una línea de texto
.SH SINOPSIS
\fBecho\fP [\fB\-ne\fP] [\fIcadena\fP ...]
.br
.B echo
{\-\-help,\-\-version}
.SH DESCRIPCIÓN
Esta documentación ha dejado de mantenerse y puede ser inexacta o estar
incompleta. La documentación Texinfo es ahora la fuente autorizada.
.PP
Esta página de manual documenta la versión GNU de
.BR echo .
Tenga en cuenta que la mayor parte de los shell incorporan una orden con el 
mismo nombre y funcionamiento análogo.
.PP
.B echo
escribe cada una de las \fIcadenas\fP dadas en su salida estándar, con un espacio
en blanco entre cada una y un carácter "salto de línea" después de la última
cadena.
.SS OPCIONES
.TP
.I \-n
No enviar el carácter "salto de línea" al final.
.TP
.I \-e
Activa la interpretación en las cadenas de los siguientes caracteres precedidos 
por una barra invertida:
.RS
.PD 0
.TP
.B \ea
alarma (timbre)
.TP
.B \eb
espacio atrás
.TP
.B \ec
suprime el "salto de línea" final
.TP
.B \ef
salto de página
.TP
.B \en
salto de línea
.TP
.B \er
retorno de carro
.TP
.B \et
tabulado horizontal
.TP
.B \ev
tabulado vertical
.TP
.B \e\e
barra invertida
.TP
.B \ennn
el carácter cuyo código ASCII es \fInnn\fP (en octal)
.PD
.RE
.SS OPCIONES
Cuando se ejecuta el programa GNU
.B echo
con exactamente un parámetro, se reconocen las siguientes opciones:
.TP
.I "\-\-help"
Muestra un mensaje de uso en la salida estándar y termina sin errores.
.TP
.I "\-\-version"
Muestra información acerca de la versión del programa en la salida estándar
y termina sin errores.
