.\" -*- nroff -*-
.\"Traducida por Pedro Pablo Fábrega, Julio 98 <pfabrega@arrakis.es>"
.TH FALSE 1 "Utilidades Shell GNU" "FSF"
.SH NOMBRE
false \- no hace nada, fallo
.SH SINOPSIS
.B false
.br
.B false
{\-\-help,\-\-version}
.SH DESCRIPCIÓN
Esta documentación no será mantenida y puede ser inexacta o incompleta.
La documentación Texinfo es ahora la fuente autorizada.
.PP
Esta página de manual documenta la versión GNU de
.B false
(y probablemente cualquier otra versión también).
.B false
no hace nada salvo devolver un estado de terminación 1, que significa 
``fallo''. Se puede usar en los guiones shell donde se necesite un 
comando que falle.
.SS OPCIONES
Cuando GNU
.B false
se llama con sólo un argumento, reconoce las siguientes opciones:
.TP
.I "\-\-help"
Imprime un mensaje de uso en la salida estándar y termina correctamente.
.TP
.I "\-\-version"
Imprime información sobre la versión en la salida estándar y termina
correctamente.
