.\"
.\" Translated 3 Jan 1998 by Juan José López Mellado
.\"   (laveneno@hotmail.com)
.\"
.TH IGAWK 1 "13 Oct 1995" "Free Software Foundation" "Órdenes de Utilidad"
.SH NOMBRE
igawk \- gawk con ficheros de inclusión
.SH SINOPSIS
.B igawk
[ opciones de
.I gawk
]
.B \-f
.I fichero-de-programa
[
.B \-\^\-
] fichero .\^.\^.
.br
.B igawk
[ opciones de
.I gawk
]
[
.B \-\^\-
]
.I texto-de-programa
fichero .\^.\^.
.SH DESCRIPCIÓN
.I Igawk
es un simple script de shell que añade la capacidad de tener ``ficheros
de inclusión'' con
.IR gawk (1).
.PP
Los programas AWK para
.I igawk
son los mismos que para 
.IR gawk ,
con la única excepción de que puede añadir líneas como
.RS
.sp
.ft B
@include getopt.awk
.ft R
.sp
.RE
en su programa para incluir el fichero
.B getopt.awk
desde el directorio actual o cualquier otro del camino de búsqueda.
.SH OPCIONES
Vea
.IR gawk (1)
para obtener una completa descripción del lenguaje AWK y de las
opciones que soporta
.I gawk .
.SH EJEMPLOS
.nf
.ft B
cat << EOF > test.awk
@include getopt.awk
.sp
BEGIN {
	while (getopt(ARGC, ARGV, "am:q") != \-1)
		\&.\^.\^.
}
EOF
.sp
igawk \-f test.awk
.ft R
.fi
.SH VÉASE TAMBIÉN
.IR gawk (1)
.PP
.IR "AWK Language Programming" ,
Edition 1.0, publicado por la Free Software Foundation, 1995.
.SH AUTOR
Arnold Robbins
.RB ( arnold@gnu.ai.mit.edu ).
