.\" @(#)kbd_mode.1 1.0 940406 aeb
.\"
.\" Translated into Spanish on Sat Dec 5 1998 by Gerardo Aburruzaga
.\" García <gerardo.aburruzaga@uca.es>
.\"
.TH KBD_MODE 1 "6 de Abril de 1994"
.SH NOMBRE
kbd_mode \- dice o establece el modo de teclado
.SH SINOPSIS
.B kbd_mode
[
.I -a | -u | -k | -s 
]
.SH DESCRIPCIÓN
.IX "orden kbd_mode" "" "orden \fLkbd_mode\fR"  
.LP
Sin argumentos,
.B kbd_mode
muestra el modo actual de teclado (RAW, MEDIUMRAW o XLATE).
Con un argumento, establece el modo del teclado según se indica:
.LP
\-s: modo de código de rastreo (RAW, CRUDO),
.LP
\-k: modo de código de tecla (MEDIUMRAW, MEDIO CRUDO),
.LP
\-a: modo ASCII (XLATE),
.LP
\-u: modo UTF-8 (UNICODE).
.LP
Por supuesto el "\-a" es algo tradicional, y el código empleado puede
ser cualquier conjunto de caracteres de 8 bits. Con "\-u" se espera un
conjunto de caracteres de 16 bits. y estos caracteres se transmiten al
núcleo como 1, 2 ó 3 bytes (siguiendo la codificación UTF-8).
En estos dos últimos modos se emplea el mapa de teclado definido por
.BR loadkeys (1). 

Atención: cambiar el modo del teclado, a menos que sea entre ASCII y
Unicode, probablemente se lo dejará inutilizable.
Esta orden está pensada para su empleo (digamos mediante entrada
remota) cuando algún programa haya dejado su teclado en el estado
equivocado. Observe que en algunas versiones anticuadas de este
programa la opción "\-u" era un sinónimo de la "\-s".
.SH "VÉASE TAMBIÉN"
.BR loadkeys (1)

