.\" Traducido el vie, 25 jun 1999 por Fidel García <fidelgq@dinamic.net>
.\"{{{}}}
.\"{{{  Title
.TH MESG 1 "27 mayo 1997" "Linux" "Manual del Usuario de Linux"
.\"}}}
.\"{{{  Name
.SH NOMBRE
mesg \- controla el acceso de escritura a tu terminal
.\"}}}
.\"{{{  Synopsis
.SH SINOPSIS
.B mesg
.RB [ y | n ]
.\"}}}
.\"{{{  Description
.SH DESCRIPCIÓN
.B Mesg
controla el acceso a tu terminal por otros. Generalmente es usado para 
permitir o negar a otros usuarios la escritura en el terminal (vea \fBwrite\fP(1)).
.\"}}}
.\"{{{  Options
.SH OPCIONES
.IP \fBy\fP
Permite el acceso a escritura al terminal.
.IP \fBn\fP
Niega el acceso a escritura al terminal.
.PP
Si no se indica ninguna opción, \fBmesg\fP imprimirá el estado actual del
terminal.
.\"}}}
.\"{{{  Author
.SH AUTOR
Miquel van Smoorenburg (miquels@cistron.nl)
.\"}}}
.\"{{{  See also
.SH "VÉASE TAMBIÉN"
.BR talk (1),
.BR write (1),
.BR wall (1)
.\"}}}
