.\" Translated 10 Jun 1998 by Vicente Pastor Gómez <VPASTORG@santandersupernet.com , vicpastor@hotmail.com>
.TH MREAD 1 "29 Junio 1997" mtools-3.7
.SH NOMBRE
mread - 
'\" t
.de TQ
.br
.ns
.TP \\$1
..

.tr \(is'
.tr \(if`
.tr \(pd"

.SH NOTA
Esta página de manual ha sido generada automáticamente a partir de la
documentación texinfo de mtools. Sin embargo, el proceso es sólo aproximado, 
y algunos elementos tales como referencias
cruzadas, notas al pie e índices, se pierden en este proceso de traducción.
De hecho, estos elementos no tienen una
representación adecuada en el formato de las páginas del manual. Por otra
parte, sólo se han traducido los elemntos específicos de cada comando, y se ha
desechado de la versión de la página del manual la información general de
mtools. Por este motivo, le aviso encarecidamente que use el documento texinfo
original.
.TP
* \ \  Para generar un copia imprimible del documento texinfo use los siguientes comandos:

.nf
.ft 3
.in +0.3i
    ./configure; make dvi; dvips mtools.dvi .fi
.in -0.3i
.ft R
.lp
 
\&\fR
.TP
* \ \ 
Para generar una copia html, ejecute:
 
.nf
.ft 3
.in +0.3i
    ./configure; make html
.fi
.in -0.3i
.ft R
.lp
 
\&\fRPuede encontrar un html preconfeccionado en:
\&\fR\&\f(CW\(ifhttp://linux.wauug.org/pub/knaff/mtools\(is\fR
.TP
* \ \ 
Para generar un copia info (visualizable usando el modo info de emacs), ejecute:

.nf
.ft 3
.in +0.3i
    ./configure; make info
.fi
.in -0.3i
.ft R
.lp
 
\&\fR
.PP
El documento texinfo parece más bonito en html o cuando se imprime. De
hecho, la versión info contiene ciertos ejemplos que son difíciles de 
leer debido a las convenciones de notación usadas en info.
.PP
.SH VÉASE TAMBIÉN
Documentos texinfo de las Mtools.
