.\" -*- nroff -*-
.\"Traducida por Pedro Pablo Fábrega, Julio 98 <pfabrega@arrakis.es>"
.TH PRINTENV 1 "Utilidades Shell GNU" "FSF"
.SH NOMBRE
printenv \- imprime parte o todo el entorno
.SH SINOPSIS
.B printenv
[\-\-help] [\-\-version] [variable...]
.SH DESCRIPCIÓN
Esta documentación no será mantenida y puede ser inexacta o incompleta.
La documentación Texinfo es ahora la fuente autorizada.
.PP
Esta página de manual documenta la versión GNU de
.BR printenv .
Si no se proporcionan argumentos,
.B printenv
imprime el entorno completo.  Si se dan uno o más nombres de variables, 
imprime el valor de cada una que esté asignada, y nada para aquellas
que no tengan contenido asiganado. 
If one or more variable names are
.PP
El estado de la salida es:
.nf
0 si se encontraron todas las variables especificadas
1 si no se encontró al menos una variable especificada
2 si ocurrió un error de escritura
.SS OPCIONES
.TP
.I "\-\-help"
Imprime un mensaje de uso en la salida estándar y termina correctamente.
.TP
.I "\-\-version"
Imprime información sobre la versión en la salida estándar y termina
correctamente.
