.\" @(#)psfaddtable.1
.\"
.\" Translated into Spanish on Sat Dec 5 1998 by Gerardo Aburruzaga
.\" García <gerardo.aburruzaga@uca.es>
.\"
.TH PSFADDTABLE 1 "25 de Octubre de 1994"
.SH NOMBRE
psfaddtable \- añade una tabla de caracteres Unicode a un tipo de
letra de consola
.SH SINOPSIS
.B psfaddtable
fichero-de-tipos fichero-tabla [fichero-salida]
.LP
.SH DESCRIPCIÓN
.IX "orden psfaddtable" "" "orden \fLpsfaddtable\fR"  
.LP
.B psfaddtable
toma un tipo de letra de consola en formato .psf como el dado por
.I fichero-de-tipos
y lo mezcla con la tabla de caracteres Unicode dada en
.I fichero-tabla
para producir un fichero de tipos con una tabla de caracteres
empotrada, que se escribe en
.I fichero-salida
si se da, o si no en la salida estándar. O bien
.I fichero-de-tipos
o
.I fichero-de-salida
(pero no ambos) pueden reemplazarse por un guión (\-) para leer desde
la entrada estándar en su lugar. Si el
.I fichero-de-tipos
ya contiene una tabla de caracteres empotrada, no se tiene en
consideración. 
.SH FORMATO DEL FICHERO DE TABLA
Cada línea del 
.I fichero-tabla
debe estar o bien en blanco, o contener un comentario (precedido por
.IR # ),
o contener una secuencia de números en base diez (predeterminada),
octal 
(precedidos por
.IR 0 ),
o hexadecimal (precedidos por
.IR 0x ).
El primer número de cada línea indica el índice del signo gráfico en
el tipo al cual nos estamos refiriendo, que estará entre 0 y 0xff para
un tipo de letra de 256 caracteres y entre 0 y 0x1ff para uno de 512. 
Cualesquiera otros números en la misma línea son Unicodes que
corresponden a este índice de signo gráfico específico. Es permisible
que haya varias líneas para el mismo signo.
.SH "VÉASE TAMBIÉN"
.BR setfont (8),
.BR psfgettable (1),
.BR psfstriptable (1)


