.\" -*- nroff -*-
.\"Traducida por Pedro Pablo Fábrega, Julio 98 <pfabrega@arrakis.es>"
.TH PWD 1 "Utilidades Shell GNU" "FSF"
.SH NOMBRE
pwd \- imprime el nombre del directorio de trabajo actual (print working 
directory)
.SH SINOPSIS
.B pwd
.br
.B pwd
{\-\-help,\-\-version}
.SH DESCRIPCION
Esta documentación no será mantenida y puede ser inexacta o incompleta.
La documentación Texinfo es ahora la fuente autorizada.
.PP
Esta página de manual documenta la versión GNU de
.BR pwd .
.B pwd
imprime el nombre del directorio actual completamente resuelto.
Esto es, todos los componentes del nombre impreso serán los nombres de 
directorios actuales  \-\- nada serán enlace simbólicos.
.PP
Observe que la mayoría de las shell Unix proporcionan un comando 
.B pwd
con una funcionalidad similar, y por tanto el comando interactivo sin nada
más que 
.B pwd
normalmente ejecutará la versión integrada en la shell y no ésta.
.SS OPCIONES
.TP
.I "\-\-help"
Imprime un mensaje de uso en la salida estándar y termina correctamente.
.TP
.I "\-\-version"
Imprime información sobre la versión en la salida estándar y termina
correctamente.
