.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\"
.\" Translated on 22 Aug 1998 by Juan José López Mellado
.\"              (laveneno@hotmail.com)
.\"
.TH RESET 1 "10 Octubre 1993" "Linux 0.99" "Manual del Programador de Linux"
.SH NOMBRE
reset \- restaurar el terminal
.SH SINOPSIS
.BR reset
.SH DESCRIPCIÓN
.B reset
llama a
.BR tput (1)
con los argumentos
.IR clear , rmacs , rmm , rmul , rs1 , rs2 " y " rs3 .
Esto provoca que
.B tput
envíe las cadenas de restauración al terminal basándose en la información
de
.I /etc/termcap
(para el
.BR tput 
de GNU o BSD)
o en la base de datos terminfo (para el 
.BR tput
de
.B ncurses ).

Esta secuencia parece ser suficiente para restaurar la Consola Virtual de
Linux cuando empieza a escribir caracteres extraños. Como medida de
precaución, también se llama a
.BR stty (1)
con el argumento
.I sane
en un intento por volver al modo ``cooked'' (interpretado).
.SH "VÉASE TAMBIÉN"
.BR clear (1),
.BR stty (1),
.BR tput (1)
.SH AUTOR
Rik Faith (faith@cs.unc.edu)
