.\" @(#)tar.1 1.11.1 93/19/22 PJV;
.\" Translated into Spanish on Mon Jul 27 1998 by Gerardo Aburruzaga
.\" García <gerardo@cica.es>
.\"
.TH TAR 1 "22 Septiembre 1993"
.SH NOMBRE
tar \- La versión de GNU de la utilidad tar para archivar
.SH SINOPSIS
.B tar
[
.B \-
]
.B A --catenate --concatenate \||\| c --create \||\| d --diff --compare \||\| r --append \||\| t --list \||\| u --update \||\| x -extract --get
[
.B --atime-preserve
]
[
.B -b, --block-size N
]
[
.B -B, --read-full-blocks
]
[
.B -C, --directory DIR
]
[
.B --checkpoint 
]
[
.B -f, --file [ANFITRIÓN:]F
]
[
.B --force-local 
]
[
.B -F, --info-script F --new-volume-script F
]
[
.B -G, --incremental
]
[
.B -g, --listed-incremental F
]
[
.B -h, --dereference
]
[
.B -i, --ignore-zeros
]
[
.B --ignore-failed-read
]
[
.B -k, --keep-old-files
]
[
.B -K, --starting-file F
]
[
.B -l, --one-file-system
]
[
.B -L, --tape-length N
]
[
.B -m, --modification-time
]
[
.B -M, --multi-volume
]
[
.B -N, --after-date FECHA, --newer FECHA
]
[
.B -o, --old-archive, --portability
]
[
.B -O, --to-stdout
]
[
.B -p, --same-permissions, --preserve-permissions
]
[
.B -P, --absolute-paths
]
[
.B --preserve 
]
[
.B -R, --record-number
]
[
.B --remove-files
]
[
.B -s, --same-order, --preserve-order
]
[
.B --same-owner
]
[
.B -S, --sparse
]
[
.B -T, --files-from F
]
[
.B --null 
]
[
.B --totals 
]
[
.B -v, --verbose
]
[
.B -V, --label NOMBRE
]
[
.B --version 
]
[
.B -w, --interactive, --confirmation
]
[
.B -W, --verify 
]
[
.B --exclude FICHERO
]
[
.B -X, --exclude-from FICHERO
]
[
.B -Z, --compress, --uncompress
]
[
.B -z, --gzip, --ungzip 
]
[
.B --use-compress-program PROG
]
[
.B --block-compress
]
[
.B -[0-7][lmh] 
]
.TP
.I nombre-fichero1 [ nombre-fichero2, ... nombre-ficheroN ] 
.TP
.I directorio1 [ directorio2, ...directorioN ]
.SH DESCRIPCIÓN
.LP
Esta página del Manual documenta la versión de GNU de
.BR tar ,
un programa archivador diseñado para almacenar y extraer ficheros de
un fichero archivo conocido como un
.IR archivo-tar.
.\" %%% Añadido por el traductor
.PP
Esta página no es más que un simple resumen de las opciones de 
.BR tar ,
análogo a lo que se obtiene con la opción
.IR --help .
La información más precisa y completa se encuentra accesible mediante
el sistema 
.IR Info .
.PP
.\" %%% Fin del añadido 
Un
.IR archivo-tar 
puede crearse sobre una unidad de cinta magnética; sin embargo,
también es común en estos días escribir un
.IR archivo-tar
en un archivo normal.
El primer argumento de 
.B tar
debe ser una de las opciones:
.BR Acdrtux ,
seguido por cualesquiera argumentos opcionales que modifican el
comportamiento predeterminado.
Los últimos argumentos de
.B tar
son los nombres de los ficheros o directorios que deberán ser
archivados. El empleo de un nombre de directorio siempre implica que
los subdirectorios por debajo de él deben incluirse en el archivo.
.SH "LETRAS DE FUNCIÓN"
.TP
.B Debe emplearse sólo una de las siguientes opciones:
.TP
.B -A, --catenate, --concatenate
añade ficheros tar a un archivo
.TP
.B -c, --create 
crea un nuevo archivo
.TP
.B -d, --diff, --compare
busca diferencias entre el archivo y el sistema de ficheros
.TP
.B --delete  
borra del archivo (¡no para cintas magnéticas!)
.TP
.B -r, --append  
añade ficheros al final del archivo
.TP
.B -t, --list  
lista los contenidos de un archivo
.TP
.B -u, --update  
sólo añade ficheros que son más recientes que la copia en el archivo
.TP
.B -x, --extract, --get  
extrae ficheros de un archivo
.SH "OTRAS OPCIONES"
.TP
.B --atime-preserve
no cambia los tiempos de acceso en ficheros volcados en un archivo
.TP
.B -b, --block-size N 
tamaño de bloque de N×512 bytes (por omisión, N=20)
.TP
.B -B, --read-full-blocks 
agrupa en bloques la lectura mientras lee (para leer tuberías 4.2BSD)
.TP 
.B -C, --directory DIR 
cambia al directorio DIR
.TP 
.B --checkpoint  
muestra los nombres de directorio mientras lee el archivo
.TP
.B -f, --file [ANFITRIÓN:]F
emplea el archivo o dispositivo F en el computador ANFITRIÓN (el valor
predeterminado suele ser /dev/rmt0, la cinta magnética, pero en el
\fBtar\fP de GNU es la entrada estándar). Si F es `-', significa la
entrada o salida estándar. 
.\" He cambiado lo anterior. El original era simplemente:
.\" use archive file or device F (default /dev/rmt0)
.TP
.B --force-local  
el archivo es local incluso si tiene dos puntos
.TP 
.B -F, --info-script F --new-volume-script F 
ejecuta el guión F al final de cada cinta (implica -M)
.TP
.B -G, --incremental 
crea/lista/extrae una copia incremental en el formato antiguo de GNU
.TP
.B -g, --listed-incremental
crea/lista/extrae una copia incremental en el formato nuevo de GNU
.TP 
.B -h, --dereference 
no vuelca enlaces simbólicos, sino los ficheros reales a los que apunten
.TP
.B -i, --ignore-zeros 
no hace caso de bloques de ceros en el archivo (normalmente significan
EOF)
.TP
.B --ignore-failed-read 
no sale con estado distinto de cero (error) en el caso de encontrar
ficheros que no pueda leer
.TP
.B -k, --keep-old-files 
mantiene los ficheros existentes; no los sobreescribe en el archivo
.TP
.B -K, --starting-file F 
empieza en el fichero F en el archivo
.TP
.B -l, --one-file-system 
se queda en un sistema de ficheros local cuando crea un archivo
.TP
.B -L, --tape-length N 
pide cambio de cintas tras leer N×1024 bytes
.TP
.B -m, --modification-time 
no extrae el tiempo modificado del fichero
.TP
.B -M, --multi-volume 
crea/lista/extrae un archivo multi-volumen
.TP
.B -N, --after-date FECHA, --newer FECHA 
sólo almacena ficheros más recientes que FECHA
.TP
.B -o, --old-archive, --portability 
escribe un archivo en el formato de V7, en vez del ANSI
.TP
.B -O, --to-stdout  
extrae ficheros a la salida estándar
.TP
.B -p, --same-permissions, --preserve-permissions 
extrae toda la información de protecciones o permisos
.TP
.B -P, --absolute-paths 
no quita las '/'s del principio de nombres de ficheros
.TP
.B --preserve  
como -p -s
.TP
.B -R, --record-number 
muestra el número de registro dentro del archivo con cada mensaje
.TP 
.B --remove-files  
borra ficheros tras añadirlos al archivo
.TP
.B -s, --same-order, --preserve-order 
la lista de nombres a extraer se ordena para concordar con el archivo
.TP
.B --same-owner  
crea los ficheros extraídos con el mismo propietario
.TP
.B -S, --sparse  
maneja los ficheros dispersos eficientemente
.TP 
.B -T, --files-from F 
obtiene los nombres a extraer o crear del fichero F
.TP
.B --null   
-T lee nombres terminados en cero, anula -C
.TP
.B --totals  
muestra el número total de bytes escritos con --create
.TP
.B -v, --verbose  
lista prolijamente los ficheros procesados
.TP
.B -V, --label NOMBRE
crea un arcico con el nombre de volumen NOMBRE
.TP 
.B --version  
muestra el número de versión del programa tar
.TP
.B -w, --interactive, --confirmation 
pide confirmación para cada acción
.TP
.B -W, --verify  
intenta verificar el archivo tras escribirlo
.TP
.B --exclude FICHERO
excluye el fichero FICHERO
.TP
.B -X, --exclude-from FICHERO
excluye ficheros listados en FICHERO
.TP
.B -Z, --compress, --uncompress       
filtra el archivo a través de compress
.TP 
.B -z, --gzip, --ungzip  
filtra el archivo a través de gzip
.TP
.B --use-compress-program PROG
filtra el archivo a través del programa PROG (que debe aceptar -d)
.TP
.B --block-compress 
agrupa en bloques la salida del programa de compresión para cintas
.TP
.B -[0-7][lmh]  
especifica la unidad de cinta y la densidad
