.\" -*- nroff -*-
.\"Translated 21 Jul 1998 by Javi Diaz (javid@si.upc.es)
.TH TEE 1 "Utilidades Shell de GNU" "FSF"
.SH NOMBRE
tee \- lee de la entrada estándar y escribe en la salida estándar
y en ficheros
.SH SINOPSIS
.B tee
[\-ai] [\-\-append] [\-\-ignore-interrupts] [\-\-help] [\-\-version] [fich...]
.SH DESCRIPCIÓN
Este documento ya no es mantenido y puede ser impreciso o incompleto. La
documentación de Texinfo es ahora la fuente de información recomendada.
.PP
Esta página del manual documenta la versión GNU de
.BR tee .
El comando
.B tee
copia su entrada estándar a su salida estándar y a todos los ficheros
pasados como argumentos.
.P
Si alguno de los ficheros a escribir no existe todavía, será es creado. Si
alguno de los ficheros a escribir ya existe, los datos que éste contenía
son sobreescritos almenos que la opción
.I \-a
sea usada.
.SS OPCIONES
.TP
.I "\-a, \-\-append"
Añade la entrada estándar a los ficheros pasados en vez de sobreescribirlos.
.TP
.I "\-\-help"
Escribe un mensaje sobre el uso en la salida estándar y acaba sin
provocar error.
.TP
.I "\-i, \-\-ignore-interrupts"
Ignora las señales de interrupción.
.TP
.I "\-\-version"
Escribe información sobre la versión en la salida estándar y acaba sin
provocar error.
