.\"Traducida por Pedro Pablo Fábrega, Febrero 99 <pfabrega@arrakis.es>"
.\"             -*-Nroff-*-
.\"  Esta página Copyright (C) 1993 Matt Welsh, mdw@tc.cornell.edu.
.\"  Distribuible Libremente bajo los términos de GPL
.TH TLOAD 1 "20 Marzo 1993 " "Cohesive Systems" "Manual del Programador Linux"
.SH NAME
tload \- representación gráfica de la carga promedio del sistema
.SH SINOPSIS
.B tload
.RB [ "\-V" "] [" "\-s"
.IR scala "] ["
.BI "\-d" " retardo"
.RI "] [" tty ]
.SH DESCRIPCIÓN
\fBtload\fP imprime un gráfico del promedio de carga del sistema actual 
en la \fItty\fP especificada (o la tty del proceso tload si no se especifica 
ninguna).
.SS Opciones
La opción
.BI "\-s" " scala"
permite especificar una escala vertical para la salida (en caracteres entre 
marcas gráficas); así, un valor más pequeño representa una escala más grande, 
y viceversa.

El
.BI "\-d" " retardo"
fija el retardo entre actualizaciones gráficas en segundos.
.PP
.SH FICHEROS
.I /proc/loadavg
información de la carga promedio

.SH "VÉASE TAMBIÉN"
.BR ps (1),
.BR top (1),
.BR uptime (1),
.BR w (1)

.SH FALLOS(BUGS)
La opción
.BI "\-d" " retardo"
fija el argumento tiempo para 
.BR alarm (2);
si se especifica -d 0, la alarma se pone a 0, con lo cual nunca se enviará la 
.B SIGALRM
ni se actualizará el gráfico.

.SH AUTORES
Branko Lankester, David Engel <david@ods.com>, y
Michael K. Johnson <johnsonm@redhat.com>.

Por favor envíe los informes de bug a <procps-bugs@redhat.com>
