.\" -*- nroff -*-
.\"
.\" Translated 29 Jul 1998 by Juan José López Mellado (laveneno@hotmail.com)
.\"
.TH TTY 1 "Utilidades Shell de GNU" "FSF"
.SH NOMBRE
tty \- imprime el nombre del fichero del terminal conectado a la
entrada estándar
.SH SINOPSIS
.B tty
[\-s] [\-\-silent] [\-\-quiet] [\-\-help] [\-\-version]
.SH DESCRIPCIÓN
Esta documentación no va a ser mantenida a partir de ahora y puede
ser inexacta o incompleta. La documentación Texinfo es ahora la
fuente autorizada.
.PP
Esta página de manual documenta la versión de GNU de
.BR tty .
.B tty
imprime el nombre del fichero del tty conectado a su entrada estándar.
Imprime `not a tty' si la entrada estándar no es una tty. Acaba con
los siguientes valores:
.nf
0 si la entrada estándar es una tty
1 si la entrada estándar no es una tty
2 si se le dieron argumentos incorrectos
3 si ocurrieron errores de escritura
.fi
.SS OPCIONES
.TP
.I "\-\-help"
Imprime un mensaje del uso por la salida estándar y termina
satisfactoriamente.
.TP
.I "\-s, \-\-silent, \-\-quiet"
No imprime nada; solo retorna un valor de terminación correcta.
.TP
.I "\-\-version"
Imprime información sobre la versión por la salida estándar y
termina satisfactoriamente.
