.\"Traducida por Pedro Pablo Fábrega, Febrero 99 <pfabrega@arrakis.es>"
.\"             -*-Nroff-*-
.\"
.TH WATCH 1 "2 Septiembre 1997" "Linux" "Manual del Progrmador Linux"
.SH NOMBRE
watch \- muestra un programa con intervalos de actualización
.SH SINOPSIS
.B watch
[-n]
.I segundos programa
[
.I argumentos ...
]
.SH DESCRIPCIÓN
.B "watch "
es un programa basado en curses (3) que le permite mostrar un programa 
mientras cambia. Por defecto, se actualiza  el solo cada 2 segundos. Puede 
especificar el número de segundos con la opción -n. Los paquetes curses 
permiten una actualización rápida de la pantalla mediante la  optimización 
del cursor. El programa finalizará con una interrupción de teclado, que 
dejará la pantalla en un estado limpio y válido. 

.SH AUTORES
.B watch
lo escribió Tony Rems <rembo@unisoft.com>
