.\" Translated 12 Jun 1998 by Vicente Pastor Gómez <VPASTORG@santandersupernet.com , vicpastor@hotmail.com>
.TH ZDIFF 1
.SH NOMBRE
zcmp, zdiff \- comparar ficheros comprimidos
.SH SINOPSIS
.B zcmp
[ cmp_opciones ] fichero1
[ fichero2 ]
.br
.B zdiff
[ diff_opciones ] fichero1
[ fichero2 ]
.SH DESCRIPCIÓN
.I  Zcmp
y
.I zdiff
se usan para invocar los programas
.I cmp
o
.I diff
sobre ficheros comprimidos. Todas las opciones especificadas se pasan
directamente a
.I cmp
o
.IR diff "."
Si sólo se especifica 1 fichero, entonces los ficheros comparados son
.I fichero1
y una copia descomprimida de
.IR fichero1 ".gz."
Si se especifican 2 ficheros, entonces son descomprimidos si es necesario, y
pasados a
.I cmp
o
.IR diff "."
El estado de salida de
.I cmp
o
.I diff
es preservado.
.SH "VÉASE TAMBIÉN"
cmp(1), diff(1), zmore(1), zgrep(1), znew(1), zforce(1), gzip(1), gzexe(1)
.SH FALLOS (BUGS)
Los mensajes de los programas
.I cmp
o
.I diff
se refieren a nombres de fichero temporales, en vez de a los especificados.
