.\" Translated 12 Jun 1998 by Vicente Pastor Gómez <VPASTORG@santandersupernet.com , vicpastor@hotmail.com>
.TH ZFORCE 1
.SH NOMBRE
zforce \- forzar la extensión '.gz' en todos los ficheros gzip
.SH SINOPSIS
.B zforce
[ nombre ...  ]
.SH DESCRIPCIÓN
.I  zforce
fuerza una extensión .gz en todos los ficheros
.I gzip
de modo que
.I gzip
no los comprima dos veces.
Esto puede ser útil para ficheros con nombres truncados tras una transferencia.
En sistemas con limitación para el nombre de ficheros a 14 caracteres, el
nombre original es truncado para hacer sitio al sufijo .gz. Por ejemplo,
12345678901234 es renombrado a 12345678901.gz. Un fichero con nombre foo.tgz
se dejaría intacto.
.SH "VÉASE TAMBIÉN"
gzip(1), znew(1), zmore(1), zgrep(1), zdiff(1), gzexe(1)
