.\" Translated 15 Jun 1998 by Vicente Pastor Gómez <VPASTORG@santandersupernet.com , vicpastor@hotmail.com>
.TH ZNEW 1
.SH NOMBRE
znew \-   recomprimir ficheros .Z a .gz
.SH SINOPSIS
.B znew
[ -ftv9PK] [ name.Z ...  ]
.SH DESCRIPCIÓN
.I  Znew
recomprime ficheros de formato .Z (compress) a formato .gz (gzip). Si se desea 
recomprimir un fichero que ya está en formato gzip, renombrar el fichero a
forzar a extensión .Z, y ejecutar znew.
.SH OPCIONES
.TP
.B \-f
Forzar recompresión de formato .Z a .gz, incluso si ya existe un fichero .gz.
.TP
.B \-t
Comprueba los nuevos ficheros antes de borrar los originales.
.TP
.B \-v
"Verbose". Muestra el nombre y porcentaje de reducción para cada fichero
comprimido.
.TP
.B \-9
Utilizar el método de compresión más lento (compresión óptima).
.TP
.B \-P
Utilizar tuberías para la conversión, para reducir el uso de espacio de disco.
.TP
.B \-K
Guardar el fichero .Z cuando es más pequeño que el fichero .gz.
.SH "VÉASE TAMBIÉN"
gzip(1), zmore(1), zdiff(1), zgrep(1), zforce(1), gzexe(1), compress(1)
.SH FALLOS
.I Znew
no mantiene la marca de hora con la opción -P si
.I cpmod(1)
no está disponible y
.I touch(1)
no soporta la opción -r.

