#!/usr/bin/perl -w

while (<>) {
 if (m/</) {
   s/<listitem>(<para>)?\n*/\n * /g; # List items become an asterisk.
   s/<[^>]*>//g;       # Remove all <..>.
   if (m/./) {print;}; # if there's a char (other than newline), print.
 } else {
   print;
 }
}
