#!/bin/bash
##
# Código fuente LuCAS V3
# Copyright (C) 1999 Hispalinux / Juan J. Amor / Ismael Olea
# Programa bajo la proteccion de GPL 2.0
##
# $Id: haz_dep_wml,v 1.1.1.1 2000/07/10 17:49:08 jjamor Exp $
##

DIR_MAKEFILE=`pwd`

# Generacion de dependencias (objetivos html) a partir de los wml existentes
echo -n 'all: '  > ${DIR_MAKEFILE}/.dependencias

for var in `ls *.wml`
do
    nombre=`basename $var .wml`

    case $nombre in
      Icabecera | Imenu | Ipie) ;;
      index) echo -n "\$(DIR_TARGET)/$nombre.html " >> ${DIR_MAKEFILE}/.dependencias ;;
      *) echo -n "\$(DIR_TARGET)/htmls/$nombre.html " >> ${DIR_MAKEFILE}/.dependencias ;;
    esac

done

# Fin de linea all:
echo "" >> ${DIR_MAKEFILE}/.dependencias
echo "" >> ${DIR_MAKEFILE}/.dependencias

# Generacion de la variable INCL_COMOS a partir de los COMOs existentes
DIR_COMOS='../../COMO-INSFLUG/es'

echo -n 'INCL_COMOS = ' >> ${DIR_MAKEFILE}/.dependencias

# Los comos
cd ${DIR_COMOS}

for var in `ls`
do
    case $var in
      LEAME | TODO | dvi | ps | mini | html | sgml | txt | rtf | pdf) ;;
      *) echo -n "${DIR_COMOS}/$var " >> ${DIR_MAKEFILE}/.dependencias ;;
    esac
done

# Los minicomos
cd mini

for var in `ls`
do
    case $var in
      LEAME | TODO | dvi | ps | mini | html | sgml | txt | rtf | pdf) ;;
      *) echo -n "${DIR_COMOS}/mini/$var " >> ${DIR_MAKEFILE}/.dependencias ;;
    esac
done

