#!/bin/sh
##
# Código fuente LuCAS V3
# Copyright (C) 1999 Hispalinux / Juan J. Amor / Ismael Olea
# Programa bajo la proteccion de GPL 2.0
##
# $Id: tounix,v 1.1.1.1 2000/07/10 17:49:08 jjamor Exp $
##
#
# Este script elimina el caracter de retorno de carro de los
# ficheros WML
#

for var in `ls *.wml`
do
   tr -d '\r' < $var > $var.new
   mv -f $var.new $var
done
