.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 22 July 1995 by Michael Chastain <mec@duracef.shout.net>:
.\"   'gethostname' is real system call on Linux/Alpha.
.\" Modified Fri Jan 31 16:30:53 1997 by Eric S. Raymond <esr@thyrsus.com>
.\" Modified 2000-06-04, 2001-12-15 by aeb
.\" Translation revised May 5 1998 by Jordi Gili <jordi@enterprise.udg.es>
.\"
.TH GETHOSTNAME 2 "15 Diciembre 2001" "Linux 2.5.0" "Manual del programador de Linux"
.SH NOMBRE
gethostname, sethostname \- obtiene/asigna el nombre del host
.SH SINOPSIS
.B #include <unistd.h>
.sp
.BI "int gethostname(char *" name ", size_t " len );
.br
.BI "int sethostname(const char *" name ", size_t " len );
.SH DESCRIPCI√ìN
Estas funciones se usan para obtener o cambiar el nombre del host del
proceso actual. 
La funciÛn
.B gethostname()
devuelve un nombre de host acabado en NULL (establecido anteriormente por
.BR sethostname() )
en el array \fIname\fP que tiene una longitud de \fIlen\fP bytes.
En el caso en que el nombre de host acabado en NULL no quepa, no se devuelve
un error, pero se trunca el nombre de host. Queda sin especificar
si el nombre de host truncado terminar· en NULL.
.SH "VALOR DEVUELTO"
En caso de √©xito devuelve un 0. En caso de error,devuelve un \-1, y 
.I errno
se asigna apropiadamente.
.SH ERRORES
.TP
.B EINVAL
.I len
es negativo o, para
.BR sethostname ,
.I len
es mas largo que el m√°ximo de tama√±o permitido,
o, para
.BR gethostname
en Linux/i386,
.I len
es mas corto que el tama√±o actual.
(In this last case glibc 2.1 uses ENAMETOOLONG.)
.TP
.B EPERM
Para
.BR sethostname ,
realizar la llamada no hace falta estar como superusuario.
.TP
.B EFAULT
.I name
es una direcci√≥n inv√°lida.
.SH "CONFORME A"
SVr4, 4.4BSD  (esta funci√≥n apareci√≥ por primera vez en 4.2BSD).
POSIX 1003.1-2001 especifica
.B gethostname
pero no
.BR sethostname .
.SH FALLOS
Para muchas combinaciones n˙cleo Linux / libc
.B gethostname
devolver· un error en lugar de un nombre de host truncado.
.SH OBSERVACIONES
SUSv2 garantiza que `Los nombres de host est·n limitados a 255 bytes'.
POSIX 1003.1-2001 garantiza que `Los nombres de host (sin incluir
el car·cter NULL del final) est·n limitados a HOST_NAME_MAX bytes'.
.SH "V√âASE TAMBI√âN"
.BR getdomainname (2),
.BR setdomainname (2),
.BR uname (2)
