# Makefile.in generated automatically by automake 1.4-p5 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Normally you do not need to remake the files here. But if you want
# to you will need the GNU TeX-info utilities. To make a Postscript
# files you also need TeX and dvips. To make the PDF file you will
# need pdftex. We use the teTeX distribution for all of these.

# We avoid default automake rules because of problems with .dvi file
# and BSD makes

# If you know how to fix any of this more elegantly please mail
# docs@mysql.com


SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/mysql
pkglibdir = $(libdir)/mysql
pkgincludedir = $(includedir)/mysql

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
ALLOCA = 
AS = gcc -c
AVAILABLE_LANGUAGES = czech danish dutch english estonian french german greek hungarian italian japanese korean norwegian norwegian-ny polish portuguese romanian russian slovak spanish swedish ukrainian
AVAILABLE_LANGUAGES_ERRORS =  czech/errmsg.sys danish/errmsg.sys dutch/errmsg.sys english/errmsg.sys estonian/errmsg.sys french/errmsg.sys german/errmsg.sys greek/errmsg.sys hungarian/errmsg.sys italian/errmsg.sys japanese/errmsg.sys korean/errmsg.sys norwegian/errmsg.sys norwegian-ny/errmsg.sys polish/errmsg.sys portuguese/errmsg.sys romanian/errmsg.sys russian/errmsg.sys slovak/errmsg.sys spanish/errmsg.sys swedish/errmsg.sys ukrainian/errmsg.sys
AWK = gawk
CC = gcc
CFLAGS = -O3 -DDBUG_OFF  
CHARSETS_NEED_SOURCE =  latin1
CHARSET_OBJS = 
CHARSET_SRCS = 
CHECK_PID = /bin/kill -0 $$PID > /dev/null 2> /dev/null
CHMOD = /bin/chmod
CLIENT_EXTRA_LDFLAGS = 
CLIENT_LIBS = -lz -lcrypt -lnsl -lm 
CMP = /usr/bin/cmp
COMPILATION_COMMENT = Source distribution
CONF_COMMAND = ./configure 
CP = /bin/cp
CPP = gcc -E
CXX = g++
CXXFLAGS = -O3 -DDBUG_OFF   -fno-implicit-templates -fno-exceptions -fno-rtti
CXXLDFLAGS = 
DLLTOOL = @DLLTOOL@
DOT_FRM_VERSION = 6
FIND_PROC = /bin/ps p $$PID | grep mysqld > /dev/null
GETCONF = getconf
GXX = yes
HOSTNAME = /bin/hostname
IS_LINUX = true
KILL = /bin/kill
LD = /usr/bin/ld
LIBDL = -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIB_EXTRA_CCFLAGS = 
LM_CFLAGS = 
LN = /bin/ln
LN_CP_F = /bin/ln -s
LN_S = ln -s
MACHINE_TYPE = i686
MAINT = #
MAKE_SHELL = /bin/sh
MT_INCLUDES = 
MT_LD_ADD = 
MV = /bin/mv
MYSQLD_DEFAULT_SWITCHES = --skip-locking
MYSQLD_EXTRA_LDFLAGS = 
MYSQLD_USER = mysql
MYSQL_BASE_VERSION = 3.23
MYSQL_NO_DASH_VERSION = 3.23.51
MYSQL_SERVER_SUFFIX = 
MYSQL_TCP_PORT = 3306
MYSQL_TCP_PORT_DEFAULT = 3306
MYSQL_UNIX_ADDR = /tmp/mysql.sock
MYSQL_VERSION_ID = 32351
NOINST_LDFLAGS = 
OBJDUMP = @OBJDUMP@
PACKAGE = mysql
PDFMANUAL = manual.pdf
PERL = /usr/bin/perl
PERL5 = /usr/bin/perl
PROTOCOL_VERSION = 10
PS = /bin/ps
RANLIB = ranlib
RM = /bin/rm
SAVE_CFLAGS = 
SAVE_CXXFLAGS = 
SAVE_CXXLDFLAGS = 
SAVE_LDFLAGS = 
SED = /bin/sed
SHARED_LIB_VERSION = 10:0:0
SYSTEM_TYPE = pc-linux-gnu
TAR = gtar
TERMCAP_LIB = -lncurses
THREAD_LOBJECTS = thr_alarm.o thr_lock.o thr_mutex.o thr_rwlock.o my_pthread.o my_thr_init.o
THREAD_LPROGRAMS = test_thr_alarm test_thr_lock
VERSION = 3.23.51
WRAPLIBS = 
YACC = bison -y
bdb_includes = 
bdb_libs = 
bdb_libs_with_path = 
bench_dirs = sql-bench mysql-test
default_charset = latin1
docs_dirs = Docs
gemini_includes = 
gemini_libs = 
innodb_includes = 
innodb_libs = 
innodb_system_libs = 
linked_client_targets = linked_libmysql_sources
readline_dir = readline
readline_link = $(top_builddir)/readline/libreadline.a
server_scripts = safe_mysqld mysql_install_db
sql_client_dirs = libmysql client
sql_server_dirs = strings dbug mysys extra regex isam merge myisam myisammrg heap sql
thread_dirs = 
uname_prog = /bin/uname

TEXI2HTML_FLAGS = -iso -number
DVIPS = dvips
MAKEINFO = makeinfo
TEXINFO_TEX = Support/texinfo.tex

noinst_SCRIPTS = Support/texi2html Support/generate-text-files.pl 			Support/generate-mirror-listing.pl

info_TEXINFOS = manual.texi

targets = manual.txt mysql.info manual.html

BUILT_SOURCES = $(targets) manual_toc.html include.texi
EXTRA_DIST = $(noinst_SCRIPTS) $(BUILT_SOURCES) mysqld_error.txt INSTALL-BINARY

GT = $(srcdir)/Support/generate-text-files.pl
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
SCRIPTS =  $(noinst_SCRIPTS)

TEXI2DVI = texi2dvi
INFO_DEPS = mysql.info
DVIS = manual.dvi
TEXINFOS = manual.texi
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
.SUFFIXES: .dvi .info .ps .texi .texinfo .txi
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps Docs/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mysql.info: manual.texi
manual.dvi: manual.texi


.texi.info:
	@cd $(srcdir) && rm -f $@ $@-[0-9] $@-[0-9][0-9]
	cd $(srcdir) \
	  && $(MAKEINFO) `echo $< | sed 's,.*/,,'`

.texi.dvi:
	TEXINPUTS=$(srcdir)/Support:$$TEXINPUTS \
	  MAKEINFO='$(MAKEINFO) -I $(srcdir)' $(TEXI2DVI) $<

.texi:
	@cd $(srcdir) && rm -f $@ $@-[0-9] $@-[0-9][0-9]
	cd $(srcdir) \
	  && $(MAKEINFO) `echo $< | sed 's,.*/,,'`

.texinfo.info:
	@cd $(srcdir) && rm -f $@ $@-[0-9] $@-[0-9][0-9]
	cd $(srcdir) \
	  && $(MAKEINFO) `echo $< | sed 's,.*/,,'`

.texinfo:
	@cd $(srcdir) && rm -f $@ $@-[0-9] $@-[0-9][0-9]
	cd $(srcdir) \
	  && $(MAKEINFO) `echo $< | sed 's,.*/,,'`

.texinfo.dvi:
	TEXINPUTS=$(srcdir)/Support:$$TEXINPUTS \
	  MAKEINFO='$(MAKEINFO) -I $(srcdir)' $(TEXI2DVI) $<

.txi.info:
	@cd $(srcdir) && rm -f $@ $@-[0-9] $@-[0-9][0-9]
	cd $(srcdir) \
	  && $(MAKEINFO) `echo $< | sed 's,.*/,,'`

.txi.dvi:
	TEXINPUTS=$(srcdir)/Support:$$TEXINPUTS \
	  MAKEINFO='$(MAKEINFO) -I $(srcdir)' $(TEXI2DVI) $<

.txi:
	@cd $(srcdir) && rm -f $@ $@-[0-9] $@-[0-9][0-9]
	cd $(srcdir) \
	  && $(MAKEINFO) `echo $< | sed 's,.*/,,'`
.dvi.ps:
	$(DVIPS) $< -o $@

install-info-am: $(INFO_DEPS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(infodir)
	@list='$(INFO_DEPS)'; \
	for file in $$list; do \
	  d=$(srcdir); \
	  for ifile in `cd $$d && echo $$file $$file-[0-9] $$file-[0-9][0-9]`; do \
	    if test -f $$d/$$ifile; then \
	      echo " $(INSTALL_DATA) $$d/$$ifile $(DESTDIR)$(infodir)/$$ifile"; \
	      $(INSTALL_DATA) $$d/$$ifile $(DESTDIR)$(infodir)/$$ifile; \
	    else : ; fi; \
	  done; \
	done
	@$(POST_INSTALL)
	@if $(SHELL) -c 'install-info --version | sed 1q | fgrep -s -v -i debian' >/dev/null 2>&1; then \
	  list='$(INFO_DEPS)'; \
	  for file in $$list; do \
	    echo " install-info --info-dir=$(DESTDIR)$(infodir) $(DESTDIR)$(infodir)/$$file";\
	    install-info --info-dir=$(DESTDIR)$(infodir) $(DESTDIR)$(infodir)/$$file || :;\
	  done; \
	else : ; fi

uninstall-info:
	$(PRE_UNINSTALL)
	@if $(SHELL) -c 'install-info --version | sed 1q | fgrep -s -v -i debian' >/dev/null 2>&1; then \
	  ii=yes; \
	else ii=; fi; \
	list='$(INFO_DEPS)'; \
	for file in $$list; do \
	  test -z "$$ii" \
	    || install-info --info-dir=$(DESTDIR)$(infodir) --remove $$file; \
	done
	@$(NORMAL_UNINSTALL)
	list='$(INFO_DEPS)'; \
	for file in $$list; do \
	  (cd $(DESTDIR)$(infodir) && rm -f $$file $$file-[0-9] $$file-[0-9][0-9]); \
	done

dist-info: $(INFO_DEPS)
	list='$(INFO_DEPS)'; \
	for base in $$list; do \
	  d=$(srcdir); \
	  for file in `cd $$d && eval echo $$base*`; do \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file; \
	  done; \
	done

mostlyclean-aminfo:
	-rm -f manual.aux manual.cp manual.cps manual.dvi manual.fn manual.fns \
	  manual.ky manual.kys manual.ps manual.log manual.pg \
	  manual.toc manual.tp manual.tps manual.vr manual.vrs \
	  manual.op manual.tr manual.cv manual.cn

clean-aminfo:

distclean-aminfo:

maintainer-clean-aminfo:
	cd $(srcdir) && for i in $(INFO_DEPS); do \
	  rm -f $$i; \
	  if test "`echo $$i-[0-9]*`" != "$$i-[0-9]*"; then \
	    rm -f $$i-[0-9]*; \
	  fi; \
	done
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = Docs

distdir: $(DISTFILES)
	$(mkinstalldirs) $(distdir)/Support
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-info
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
info-am: $(INFO_DEPS)
info: info-am
dvi-am: $(DVIS)
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-info-am
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-info
uninstall: uninstall-am
all-am: Makefile $(INFO_DEPS) $(SCRIPTS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(infodir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
mostlyclean-am:  mostlyclean-aminfo mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-aminfo clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-aminfo distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-aminfo maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: install-info-am uninstall-info mostlyclean-aminfo \
distclean-aminfo clean-aminfo maintainer-clean-aminfo tags distdir \
info-am info dvi-am dvi check check-am installcheck-am installcheck \
install-exec-am install-exec install-data-am install-data install-am \
install uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


all:			$(targets) txt_files

txt_files:		../INSTALL-SOURCE ../COPYING ../COPYING.LIB \
			../MIRRORS INSTALL-BINARY

CLEAN_FILES:		$(BUILD_SOURCES)
	touch $(BUILD_SOURCES)

# The PostScript and PDF version are so big that they are not included in the
# standard distribution. It is available for download from the home page.  
paper: manual_a4.ps manual_letter.ps  $(PDFMANUAL)

#########################################################################

# The Makefile contains the previous version so we can not use that
include.texi:	../configure.in
	echo "@c This file is autogenerated by the Makefile" > $@
	echo -n "@set mysql_version " >> $@
	grep "AM_INIT_AUTOMAKE(mysql, " ../configure.in | \
	 sed -e 's;AM_INIT_AUTOMAKE(mysql, ;;' -e 's;);;' >> $@
	echo -n "@set default_port " >> $@
	grep "MYSQL_TCP_PORT_DEFAULT=" ../configure.in | \
	 sed -e 's;MYSQL_TCP_PORT_DEFAULT=;;' >> $@

mysql.info:	manual.texi include.texi
	cd $(srcdir) && $(MAKEINFO) --no-split -I $(srcdir) $<

manual.txt:	manual.texi include.texi
	cd $(srcdir) && \
	$(MAKEINFO) -I $(srcdir) --no-headers --no-split --output $@ $<

manual.html:	manual.texi include.texi $(srcdir)/Support/texi2html
	cd $(srcdir) && /usr/bin/perl $(srcdir)/Support/texi2html $(TEXI2HTML_FLAGS) $<

manual_toc.html: manual.html

# Fix: add --output-comment with some interesting info?
# Fix: @image worked with a older version of pdftex. 
# Note: @image will work if we first convert all images to pdf ...
#       is that worth it?
# Comment: We need to run pdftex 2 times to get the cross references right.
manual.pdf: manual.texi
	cat manual.texi | sed -e 's|@image{[^}]*} *||g' > manual-tmp.texi
	pdftex --interaction=nonstopmode manual-tmp.texi
	texindex manual-tmp.??
	pdftex --interaction=nonstopmode manual-tmp.texi
	texindex manual-tmp.??
	pdftex --interaction=nonstopmode manual-tmp.texi
	mv manual-tmp.pdf manual.pdf
	rm -f manual-tmp.*
	touch $@

# Target to produce NuSphere Manual
nusphere.pdf: manual.texi
	cat manual.texi \
	| sed -e 's/@example/@smallexample/g' \
	      -e 's/@end example/@end smallexample/g' \
	      -e 's/@c ifnusphere //g' \
	      -e 's|@image{[^}]*} *||g' \
	> manual-tmp.texi
	pdftex --interaction=nonstopmode manual-tmp.texi
	texindex manual-tmp.??
	pdftex --interaction=nonstopmode manual-tmp.texi
	texindex manual-tmp.??
	pdftex --interaction=nonstopmode manual-tmp.texi
	mv manual-tmp.pdf nusphere.pdf
	rm -f manual-tmp.*
	touch $@

# Target to produce DocBook XML
mysql.xml: manual.texi include.texi
	$(MAKEINFO) --force --no-ifinfo --docbook manual.texi

# The texi2dvi gives a lot of harmless errors. Just ignore them unless
# you want to help with the typesetting part.
# This is the European papersize version
manual_a4.ps:	manual.texi include.texi
	TEXINPUTS=$(srcdir):$$TEXINPUTS \
	  MAKEINFO='$(MAKEINFO) -I $(srcdir)' \
	    $(TEXI2DVI) --batch --texinfo --quiet '@afourpaper' $<
	$(DVIPS) -t a4 manual.dvi -o $@
	touch $@

# This is the American papersize version
manual_letter.ps:	manual.texi include.texi
	TEXINPUTS=$(srcdir):$$TEXINPUTS \
	  MAKEINFO='$(MAKEINFO) -I $(srcdir)' \
	    $(TEXI2DVI) --batch $<
	$(DVIPS) -t letter manual.dvi -o $@
	touch $@

# Include images for the manual in the distribution
dist-hook:
	BD=`cd $(top_srcdir); pwd`; \
	if test ! -d $(distdir)/Flags; then mkdir -p $(distdir)/Flags; fi; \
	$(INSTALL_DATA) $(srcdir)/Flags/*.gif $(srcdir)/Flags/*.eps \
		$(srcdir)/Flags/*.txt $(distdir)/Flags;
	echo "PostScript and PDF versions suitable for printing" \
		> $(distdir)/manual.ps
	echo "are available from http://www.mysql.com/Manual/" \
		>> $(distdir)/manual.ps
	echo "or any mirror site" \
		>> $(distdir)/manual.ps

../INSTALL-SOURCE:	mysql.info $(GT)
	perl -w $(GT) mysql.info "Installing" "Compatibility" > $@

# We put the description for the binary installation here so that
# people who download source wont have to see it. It is moved up to
# the toplevel by the script that makes the binary tar files.
INSTALL-BINARY:	mysql.info $(GT)
	perl -w $(GT) mysql.info "Installing binary" "Installing source" > $@

../COPYING:		mysql.info $(GT)
	perl -w $(GT) mysql.info "GPL license" "LGPL license" > $@

../COPYING.LIB:		mysql.info $(GT)
	perl -w $(GT) mysql.info "LGPL license" "Function Index" > $@

../MIRRORS:		manual.texi $(srcdir)/Support/generate-mirror-listing.pl
	perl -w $(srcdir)/Support/generate-mirror-listing.pl manual.texi > $@

# Don't update the files from bitkeeper
%::SCCS/s.%

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
