.\" Translated Sep, 21 1998 by Julio Gonzalez Duran <jugonzalez@ts.es>
.\"
.Id $Id: at_allow.5,v 1.1.1.1 2001/11/25 17:34:18 carlos Exp $
.TH AT_ACCESS 5 "Septiembre 1997" "Linux" "Manual del Programador de Linux"
.SH NOMBRE
at.acess, at.deny \- determinan quién puede enviar trabajos mediante at o batch
.SH DESCRIPCIÓN
Los ficheros 
.I /etc/at.access
y
.I /etc/at.deny
determinan qué usuarios pueden enviar comandos para su ejecución posterior mediante
.B at(1)
o
.BR batch(1) .
.PP
El formato de los ficheros consiste en una lista de nombres de usuario, uno en cada línea. 
Los espacios en blanco no están permitidos.
.PP
El superusuario siampre puede utilizar 
.BR at .
.PP
Si el fichero
.I /etc/at.allow
existe, sólo los usuarios cuyos nombres se mencionan tienen permitido el uso de 
.BR at .
.PP
Si 
.I /etc/at.allow
no existe, se chequea
.IR /etc/at.deny .
.SH "VÉASE TAMBIÉN"
at(1), atrun(1), cron(1), crontab(1), atd(8)
