.\"Traducido el 23-04-1999
.\"por Antonio Aneiros
.\"aneiros1@arrakis.es
.TH ETHERS 5 "26 abril 1996" "" "Formatos de Archivo"
.SH NOMBRE \"{{{roff}}}\"{{{
ethers \- Base de datos con asociaciones de direcciones Ethernet a números
IP.
.\"}}}
.SH DESCRIPCIÓN \"{{{
\fB/etc/ethers\fP contiene direcciones Ethernet de 48 bits y sus números IP correspondientes, una línea para cada número IP:
.sp
.Rs
\fIEthernet-address\fP  \fIIP-number\fP
.RE
.sp
Los dos números se separan por un número cualquiera de caracteres de espacio o de tabulación. Un \fB#\fP al principio de la línea da comienzo a un comentario que se extiende hasta el final de la línea. La \fIEthernet-address\fP se escribe como
.IR x : x : x : x : x : x ,
donde \fIx\fP es un número hexadecimal entre \fB0\fP y \fBff\fP que representa un byte de la dirección, que está en orden de byte de red (big-endian). El \fIIP-number\fP puede ser un nombre de servidor que se puede resolver por medio de DNS o de un número separado por puntos.
.\"}}}
.SH EJEMPLOS \"{{{
08:00:20:00:61:CA  pal
.\"}}}
.SH ARCHIVOS \"{{{
/etc/ethers
.\"}}}
.SH "VÉASE TAMBIÉN" \"{{{
rarp(8)
.\"}}}
