.\" Traducido el vie, 25 jun 1999 por Fidel García <fidelgq@dinamic.net>
.TH INITSCRIPT 5 "23 diciembre 1995" "Linux" "Manual del Admistrador de Sistemas"
.SH NOMBRE
initscript \- guión que ejecuta comandos inittab.
.SH SINOPSIS
/bin/sh /etc/initscript id niveles_de_ejecucion acción proceso
.SH DESCRIPCIÓN
Cuando el guión de entorno \fI/etc/initscript\fP existe, \fBinit\fP
lo usará para ejecutar comandos para \fIinittab\fP.
Este guión puede ser usado para cosas como, por ejemplo, colocar los valores 
por defecto \fBulimit\fP y \fBumask\fP para cada proceso.
.SH EJEMPLOS
Este es un ejemplo de initscript, que se podría instalar en tu sistema como
\fI/etc/initscript.sample\fP.
.RS
.sp
.nf
.ne 7
#
# initscript   Ejecutado por init(8) para cada programa,
#              requiere un formato como el siguiente
#
#              /bin/sh /etc/initscript <id> <nivel> <acción> <proceso>
#

  # Colocamos umask para salvar el nivel, y permitir volcados de
  # memoria.
  umask 022
  ulimit -c 2097151
  PATH=/bin:/sbin:/usr/bin:/usr/sbin
  export PATH

  # Ejecutamos el programa.
  eval exec "$4"

.sp
.RE
.SH ARCHIVOS
/etc/inittab,
/etc/initscript.
.SH AUTOR
Miquel van Smoorenburg ,<miquels@cistron.nl>
.SH "VÉASE TAMBIÉN"
init(8), inittab(5).
