.\" Copyright (c) 1994 Peter Tobias <tobias@server.et-inf.fho-emden.de>
.\" This file may be distributed under the GNU General Public License.
.\" Translated 01 Jan 1999 by Javi Diaz (javid@si.upc.es)
.\"
.TH ISSUE.NET 5 "22 Mayo 1994" "Linux" "Manual del Programador de Linux"
.SH NOMBRE
issue.net \- fichero de identificación para las sesiones de telnet
.SH DESCRIPCIÓN
El fichero \fB/etc/issue.net\fP es un fichero de texto que contiene un mensaje
o una identificación del sistema que será impreso justo antes de que aparezca
el indicador de comandos (prompt) de una sesión de telnet. Puede contener
varias secuencias
.BI "%" carácter
Las siguientes secuencias son soportadas por
.BR telnetd :
.TP
.B %t
- muestra el tty actual
.TP
.B %h
- muestra el nombre del nodo (FQDN)
.TP
.B %D
- muestra el nombre de dominio NIS
.TP
.B %d
- muestra la hora y fecha actual
.TP
.B %s
- muestra el nombre del sistema operativo
.TP
.B %m
- muestra el tipo de máquina (hardware)
.TP
.B %r
- muestra el número de liberación (release) del sistema operativo
.TP
.B %v
- muestra la versión del sistema operativo
.TP
.B %%
- muestra el carácter '%'
.PP
.SH FICHEROS
/etc/issue.net
.SH "VÉASE TAMBIÉN"
.BR telnetd (8)
