.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\" 
.\" Modified Sun Jul 25 11:06:27 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated Tue Jul 23 12:41:23 1996 by Diego Novillo (diego@cs.ualberta.ca)
.\" Translation revised on Mon May 11 16:21:39 CEST 1998 by Gerardo
.\" Aburruzaga García <gerardo.aburruzaga@uca.es>
.\" 
.TH SECURETTY 5 "29 Diciembre 1992" "Linux" "Manual del Programador de Linux"
.SH NOMBRE
securetty \- fichero que lista aquellas ttys desde las que root puede entrar
.SH DESCRIPCIÓN
\fB/etc/securetty\fP lo utiliza el programa
.BR login(1);
el fichero contiene los nombres de dispositivo de líneas de tty (sin
el prefijo /dev/) que root puede 
usar para entrar en el sistema.
.SH FICHEROS
/etc/securetty
.SH "VÉASE TAMBIÉN"
.BR login (1)
