.\" Copyright (C) 2002 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" This replaces an earlier man page written by Walter Harms
.\" <walter.harms@informatik.uni-oldenburg.de>.
.\"
.\" Traducido por Miguel Pérez Ibars <mpi79470@alu.um.es> el 25-julio-2004
.\"
.TH GETUMASK 3 "25 agosto 2002" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
getumask \- obtiene la máscara de creación de ficheros
.SH SINOPSIS
.B "#include <sys/types.h>"
.br
.B "#include <sys/stat.h>"
.sp
.B "mode_t getumask(void);"
.SH DESCRIPCIÓN
Esta función devuelve la máscara de creación de ficheros actual.
Es equivalente a
.RS
.nf
mode_t getumask(void) {
	mode_t mask = umask(0);
	umask(mask);
	return mask;
}
.fi
.RE
salvo que está documentada como hilo-seguro (esto es, comparte
un bloqueo con la llamada de biblioteca
.I umask()
).
.SH OBSERVACIONES
Esta función está documentada pero no implementada todavía en glibc 2.2.5
.SH "CONFORME A"
This is a vapourware GNU extension.
.SH "VÉASE TAMBIÉN"
.BR umask (2)
