.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\" Based on glibc infopages
.\"
.\" Corrections by aeb
.\"
.\" Traducido por Miguel Pérez Ibars <mpi79470@alu.um.es> el 9-agosto-2004
.\"
.TH  NAN 3 "10 agosto 2002" "GNU" "funciones matemáticas de libc"
.SH NOMBRE
nan, nanf, nanl \- devuelven 'Not a Number'
.SH SINOPSIS
.B #include <math.h>
.sp
.BI "double nan(const char *" tagp );
.sp
.BI "float nanf(const char *" tagp );
.sp
.BI "long double nanl(const char *" tagp );
.SH DESCRIPCIÓN
These functions return a representation (determined by
.IR tagp )
of a quiet NaN. If the implementation does not support
quiet NaNs, these functions return zero.
.LP
La llamada
.I nan("secuencia-de-caracteres")
es equivalente a
.I strtod ("NAN(secuencia-de-caracters)",NULL)
y similarmente las llamadas 
.I nanf
y
.I nanl
son equivalentes a las llamadas análogas
.I strtof
y
.IR strtold .
.PP
El argumento
.I tagp
se utiliza de manera indefinida. En sistemas IEEE 754, hay muchas
representaciones de NaN, y
.I tagp
escoge una. En otros sistemas puede que no haga nada.
.SH "CONFORME A"
C99. Vea también IEC 559 y el apéndice con funciones recomendadas
de IEEE 754/IEEE 854.
.SH "VÉASE TAMBIÉN"
.BR isnan (3),
.BR strtod (3)
