.\" Hey Emacs! This file is -*- nroff -*- source.
.\" This page is in the public domain. - aeb
.\"
.TH PTSNOMBRE 3 "30 enero 2003" "PTY Control" "Manual del Programador de Linux"
.SH NOMBRE
ptsname \- obtiene el nombre de la pseudotty esclava
.SH SINOPSIS
.nf
.B #include <stdlib.h>
.sp
.BI "char *ptsname(int " fd ");"
.fi
.SH DESCRIPCIÓN
La función
.BR ptsname ()
devuelve el nombre del dispositivo pseudo-terminal esclavo (pty)
correspondiente a la pty maestra referenciada por
.IR fd .
.SH "VALOR DEVUELTO"
Cuando tiene éxito,
.BR ptsname ()
devuelve un puntero a una cadena en almacenamiento estático. Este puntero
no debe ser liberado.
.PP
En caso de fallo,
.BR ptsname ()
devuelve un puntero a NULL.
.SH "CONFORME A"
POSIX 1003.1-2001.
La función ptsname es parte del soporte pty de Unix98, véase
.BR pts (4).
.SH "VÉASE TAMBIÉN"
.BR grantpt (3),
.BR ttyname (3),
.BR pts (4)
