.\" Copyright (C) 2002 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" This replaces an earlier man page written by Walter Harms
.\" <walter.harms@informatik.uni-oldenburg.de>.
.\"
.\" Traducido por Miguel Pérez Ibars <mpi79470@alu.um.es> el 9-agosto-2004
.\"
.TH QECVT 3  "25 agosto 2002" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
qecvt, qfcvt, qgcvt \- convierten un número en coma flotante a una cadena.
.SH SINOPSIS
.B #include <stdlib.h>
.sp
.BI "char *qecvt(long double " number ", int " ndigits ", int *" decpt ,
.BI "int *" sign );
.sp
.BI "char *qfcvt(long double " number ", int " ndigits ", int *" decpt ,
.BI "int *" sign );
.sp
.BI "char *qgcvt(long double " number ", int " ndigit ", char *" buf );
.SH DESCRIPCIÓN
Las funciones
.BR qecvt ,
.BR qfcvt
y
.BR qgcvt
son idénticas a
.BR ecvt ,
.BR fcvt
y
.BR gcvt
respectivamente, salvo que éstas usan un
argumento
.IR number
de tipo
.B "long double"
Véase
.BR ecvt (3)
y
.BR gcvt (3).
.SH OBSERVACIONES
Estas funciones están obsoletas. En su lugar,
se recomienda el uso de
.IR sprintf ()
.
.SH "CONFORME A"
SysVr4.0. No está presente en las implementaciones de Unix más comunes,
pero sí en SunOS. No está soportada por libc4 ni libc5.
Está soportada por glibc.
.SH "VÉASE TAMBIÉN"
.BR ecvt (3),
.BR ecvt_r (3),
.BR gcvt (3),
.BR sprintf (3)
