.\" Copyright 2001 Andries Brouwer <aeb@cwi.nl>.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traducción revisada por Miguel Pérez Ibars <mpi79470@alu.um.es> el 3-febrero-2005
.\"
.TH RINT 3  "31 mayo 2001" "" "Manual del Programador de Linux"
.SH NOMBRE
nearbyint, nearbyintf, nearbyintl, rint, rintf, rintl \- redondean al entero más cercano
.SH SINOPSIS
.nf
.B #include <math.h>
.sp
.BI "double nearbyint(double " x );
.br
.BI "float nearbyintf(float " x );
.br
.BI "long double nearbyintl(long double " x );
.sp
.BI "double rint(double " x );
.br
.BI "float rintf(float " x );
.br
.BI "long double rintl(long double " x );
.fi
.SH DESCRIPCIÓN
Las funciones
.B nearbyint
redondean su argumento a un valor entero con formato de coma flotante,
usando la dirección actual de redondeo y sin lanzar la excepción
.I inexact.
.LP
Las funciones
.B rint
hacen lo mismo, pero lanzan la excepción
.I inexact
cuando el resultado tiene un valor distinto al del argumento.
.SH "VALOR DEVUELTO"
El valor entero redondeado. Si \fIx\fP es un entero o infinito,
se devuelve \fIx\fP tal cual.
.SH ERRORES
Sólo pueden darse los errores EDOM Y ERANGE.
Si \fIx\fP es NaN, se devuelve NaN y a
.I errno
se le asigna EDOM.
.SH OBSERVACIONES
SUSv2 y POSIX 1003.1-2001 contienen texto sobre el desbordamiento por arriba (que puede asignar a
.I errno
el valor ERANGE, o lanzar una excepción).
En la práctica, el resultado no puede desbordarse en ninguna máquina actual,
por lo que este manejo de errores no tiene mucho sentido.
(Más concretamente, el desbordamiento sólo puede producirse cuando el valor
máximo del exponente es más pequeño que el número de bits de la mantisa.
Para los números en coma flotante de 32 y 64 bits del estándar IEEE-754
el valor máximo del exponente es 128 (resp. 1024), y el número de bits de
la mantisa es 24 (resp. 53).)
.SH "CONFORME A"
La función
.B rint()
es conforme con BSD 4.3.
Las otras funciones son de C99.
.SH "VÉASE TAMBIÉN"
.BR ceil (3),
.BR floor (3),
.BR lrint (3),
.BR nearbyint (3),
.BR round (3),
.BR trunc (3)
