.\" Hey Emacs! This file is -*- nroff -*- source.
.\" This page is in the public domain. - aeb
.\"
.TH UNLOCKPT 3 "30 enero 2003" "PTY Control" "Manual del Programador de Linux"
.SH NOMBRE
unlockpt \- desbloquea un par de pseudo-terminal maestro/esclavo
.SH SINOPSIS
.nf
.B #include <stdlib.h>
.sp
.BI "int unlockpt(int " fd ");"
.fi
.SH DESCRIPCIÓN
La función
.IR unlockpt ()
desbloquea el dispositivo pseudo-terminal (pty) esclavo
que se corresponde con la pty referenciada por
.IR fd .
.PP
.IR unlockpt ()
debería ser llamada antes de abrir el lado esclavo de una pty.
.SH "VALOR DEVUELTO"
Cuando tiene éxito,
.IR unlockpt ()
devuelve 0. En otro caso, devuelve \-1 y se modifica
.I errno
con el valor apropiado.
.SH ERRORES
.TP
.B EBADF
El argumento
.I fd
no es un descriptor de fichero abierto para escritura.
.TP
.B EINVAL
El argumento 
.I fd
no está asociado con una pty maestra.
.SH "CONFORME A"
POSIX 1003.1-2001.
.SH "VÉASE TAMBIÉN"
.IR grantpt (3),
.IR ptsname (3)
