#!/bin/sh
#
# script para automatizar el mirror de LuCAS
# Ponerlo en el crontab una vez al menos cada 7 dias
# -- Javier Ribelles, <jribelles@polinux.upv.es>
# -- Basado en el Conectiva Linux Mirror Script
# -- Rik van Riel, <riel@conectiva.com.br>

# directorio donde hacer el mirror de LuCAS
LuCASDIR=/home/ftp/pub/LuCAS

# Fichero de log, se le enviara por correo si no esta vacio
LOGFILE=$HOME/LuCAS.log

# Servidor desde el que hacer el mirror
SERVER=rsync.hispalinux.es

# Repositorio en el servidor
REPOSITORY=${SERVER}::lucas

# Opciones rsync
# (Borrar ficheros viejos, hacer un mirror completo, verbose)
RSOPTS="-av --exclude=pinpanza-orig.gif --delete --delete-after"

# Direccion de correo a quien enviar la salida del script
EMAIL=ismael@olea.org


# Comprobar que solo hay un script ejecutandose al mismo tiempo
LOCKFILE=/var/run/LuCASmirror
if [ -f ${LOCKFILE} ] ; then
	echo "Mirror de LuCAS todavia ejecutandose" | mail -s "Mirror de LuCAS. Fallo del script." ${EMAIL}
	exit
fi
touch ${LOCKFILE}


# 
# Comando rsync
#

echo "LuCAS *********************** >" > ${LOGFILE}
rsync ${RSOPTS} ${REPOSITORY} ${LuCASDIR} >> ${LOGFILE} 2>&1

# Eliminar el fichero de lock despues de terminar
rm -f ${LOCKFILE}

if [ -s ${LOGFILE} ] ; then
	mail -s "Script de Mirror de LuCAS" ${EMAIL} < ${LOGFILE} > /dev/null 2>&1
fi
