.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (C) Markus Kuhn, 1996
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" 1995-11-26  Markus Kuhn <mskuhn@cip.informatik.uni-erlangen.de>
.\"      First version written
.\" Translated by Miguel A. Sepulveda <angel@vivaldi.princeton.edu>
.\" Translation revised June 9 1998 by Juan Piernas <piernas@dif.um.es>
.\"
.TH UTF-8 7 "26 Noviembre 1995" "Linux" "Manual del Programador de Linux"
.SH NOMBRE
UTF-8 \- una codificación Unicode mutibyte compatible con ASCII
.SH DESCRIPCIÓN
El conjunto de caracteres
.B Unicode
ocupa un espacio de códigos de 16 bits. La codificación
Unicode más obvia (conocida como
.BR UCS-2 )
consiste en una secuencia de palabras de 16 bits. Tales cadenas
pueden contener, como parte de muchos caracteres de 16 bits,
bytes como '\\0' or '/', que tienen un significado especial
en nombres de ficheros y en otras variables de funciones de la
biblioteca C. Además, la mayoría de las herramientas de UNIX esperan
ficheros ASCII y no pueden leer palabras de 16 bits como caracteres
sin considerables modificaciones. Por estas razones, 
.B UCS-2
no es una codificación externa apropiada de
.B Unicode
en nombres de ficheros, variables de entorno, etc. El
.BR "ISO 10646 Universal Character Set (UCS)" ,
es un superconjunto de Unicode con un espacio de códigos de hasta
31 bits y la codificación obvia para dicho conjunto,
.B UCS-4
(una secuencia de palabras de 32 bits), posee los mismos problemas.

La codificación
.B UTF-8
de
.B Unicode
y
.B UCS
carece de estos problemas y es la forma a seguir para usar el conjunto de
caracteres
.B Unicode
bajo sistemas operativos al estilo UNIX.
.SH PROPIEDADES
La codificación
.B UTF-8 
tiene los siguientes propiedades atractivas:
.TP 0.2i
*
Los caracteres
.B UCS
0x00000000 a 0x0000007f (el conjunto clásico de caracteres
.B US-ASCII
se codifican simplemente como los bytes
0x00 a  0x7f (compatibilidad con ASCII)
Esto significa que los ficheros y cadenas que contengan
solament caracteres ASCII de 7 bits tienen la misma codificación en
.B ASCII
y en
.BR UTF-8 .
.TP
*
Todos los caracteres
.B UCS
 > 0x7f se codifican como una secuencia multibyte 
formadae solamente por bytes en el rango 
0x80 a 0xfd, por tanto ningún byte
ASCII puede aparecer como parte de otro carácter y no hay problemas
con, por ejemplo,  '\\0' or '/'.
.TP
*
Se preserva la enumeración lexicográfica de las cadenas 
.B UCS-4
.
.TP
*
Los  2^31 códigos posibles UCS pueden codificarse con
.BR UTF-8 .
.TP
*
Los bytes 0xfe y 0xff no se usan nunca en la codificación
.B UTF-8
.TP
* 
El primer byte de una secuencia multibyte que represente un
carácter no ASCII
.B UCS
siempre se halla en el rango  0xc0 a 0xfd, e indica la longitud 
de la secuencia. El resto de los bytes de la secuencia se hallan en
el rango 0x80 a 0xbf. Esto permite una fácil resincronización y
resulta en una codificación sin estado y robusta frente a la
pérdida de bytes.
.TP
*
Los caracteres
.B UCS
codificados en
.B UTF-8
pueden llegar a ser de 6 bytes, no obstante los caracteres
.B Unicode
sólo pueden ser de 3 bytes a lo sumo. Como Linux usa tan solo el
subconjunto  
.B Unicode
de 16 bits de
.BR UCS ,
en Linux la secuencias multibyte
.B UTF-8
sólo pueden tener 1, 2 ó 3 bytes.
.SH CODIFICACIÓN
Las siguientes secuencias de bytes se usan para representar un
carácter. La secuencia a usar depende del código UCS correspondiente
al carácter:
.TP 0.4i
0x00000000 - 0x0000007F:
.RI 0 xxxxxxx
.TP
0x00000080 - 0x000007FF:
.RI 110 xxxxx 
.RI 10 xxxxxx
.TP
0x00000800 - 0x0000FFFF:
.RI 1110 xxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.TP
0x00010000 - 0x001FFFFF:
.RI 11110 xxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.TP
0x00200000 - 0x03FFFFFF:
.RI 111110 xx
.RI 10 xxxxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.TP
0x04000000 - 0x7FFFFFFF:
.RI 1111110 x
.RI 10 xxxxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.RI 10 xxxxxx
.PP
Las posiciones 
.I xxx
se rellenan con los bits del número de código del carcter
representado en binario. Sólo se puede usar la secuencia más corta 
que pueda representar el número de código.
.SH EJEMPLOS
El carácter
.B Unicode
0xa9 = 1010 1001 (el signo de copyright) se codifica en 
.B UTF-8
como
.PP
.RS
11000010 10101001 = 0xc2 0xa9
.RE
.PP
y el carácter 0x2260 = 0010 0010 0110 0000 (el símbolo de "distinto que") se
codifica como:
.PP
.RS
11100010 10001001 10100000 = 0xe2 0x89 0xa0
.RE
.SH ESTÁNDARES
ISO 10646, Unicode 1.1, XPG4, Plan 9.
.SH AUTOR
Markus Kuhn <mskuhn@cip.informatik.uni-erlangen.de>
.SH "VÉASE TAMBIÉN"
.B unicode(7)
