.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" Translation revised May 2 1998 by Juan Piernas <piernas@dif.um.es> with
.\" fixes from Nicolás Lichtmaier <nick@debian.org>
.\"
.TH GETPID 2 "23 Julio 1993" "Linux 0.99.11" "Manual del Programador de Linux"
.SH NOMBRE
getpid, getppid \- obtiene el identificador de proceso
.SH SINOPSIS
.B #include <unistd.h>
.sp
.B pid_t getpid(void);
.br
.B pid_t getppid(void);
.SH DESCRIPCIÓN
.B getpid
devuelve el identificador de proceso del proceso actual. (Esto es usado
normalmente por rutinas que generan nombres únicos de ficheros temporales.)
.B getppid
devuelve el identificador de proceso del padre del proceso actual.
.SH "CONFORME A"
POSIX, BSD 4.3, SVID
.SH "VÉASE TAMBIÉN"
.BR exec (3),
.BR fork (2),
.BR kill (2),
.BR mkstemp (3),
.BR tmpnam (3),
.BR tempnam (3),
.BR tmpfile (3)
