.\" Copyright (C) 1996 Andries Brouwer (aeb@cwi.nl)
.\"
.\" Esto es documentación libre ; Tu puedes redistribuirla y/o
.\" modificarla bajos los términos de las licencias públicas generales de GNU
.\" publicados por la Fundación de Libre Software ; ambos versiones 2 de
.\" la Licencia, o (dependiendo de tí)cualquier versión posterior.
.\"
.\" Las referencias de las licencias públicas generales de GNU referentes al "código objeto"
.\" y "ejecutables" están siendo interpretadas como la salida de cualquier
.\" documento formateado o sistema tipografiado, incluyendo
.\" intermediación y salidas impresas.
.\"
.\" Este manual es distribuído con la esperanza de su buen uso,
.\" pero SIN NINGUN TIPO DE GARANTIAS ; sin siquiera las garantías implicadas de
.\" COMERCIABILIDAD o AMPTITUD PARA UN PROPOSITO PATICULAR.
.\" Ver la Licencia Pública General de GNU para más detalles.
.\"
.\" Tu deberás recibir una copia de la Licencia Pública General
.\" de GNU junto con este manual ; si no, escribe a Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modificado Thu Oct 31 14:18:40 1996 by Eric S. Raymond <esr@y\thyrsus.com>
.\"
.\" Translation revised Mon Aug 17 1998 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH GETSID 2 "11 abril 1996" "Linux 1.3.85" "Manual del Programador de Linux"
.SH NOMBRE
getsid \- obtener identificador de sesión
.SH SINOPSIS
.B #include <unistd.h>
.sp
.BI "pid_t getsid(pid_t" " pid" );
.SH DESCRIPCIÓN
.B getsid(0)
devuelve el identificador de sesión del proceso invocador.
.B getsid(p)
devuelve el identificador de sesión del proceso con
identificador
.IR p .
.SH ERRORES
En caso de error, se devuelve \-1. El único error que puede ocurrir es
.BR ESRCH ,
cuando no se encontró un proceso con identificador
.I p.
.SH "CONFORME A"
SVr4, que documenta una condición de error adicional, EPERM.
.SH "VÉASE TAMBIÉN"
.BR setsid (2)
