.\" Copyright (C) 1995, Thomas K. Dyas <tdyas@eden.rutgers.edu>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Created   Sat Aug 21 1995     Thomas K. Dyas <tdyas@eden.rutgers.edu>
.\"
.\" typo corrected, aeb, 950825
.\" added layout change from joey, 960722
.\" Translated into Spanish Mon Jan 19 1998 by Gerardo Aburruzaga
.\" García <gerardo.aburruzaga@uca.es>
.\"
.TH PERSONALITY 2 "22 julio 1996" "Linux 2.0" "Manual del Programador de Linux"
.SH NOMBRE
personality \- establece el dominio de ejecución del proceso
.SH SINOPSIS
.BI "int personality(unsigned long " persona );
.SH DESCRIPCIÓN
Linux admite diferentes dominios de ejecución, o personalidades, para
cada proceso. Entre otras cosas, los dominios de ejecución le dicen a
Linux cómo asociar números de señal a acciones a tomar para cada
señal. El sistema de dominios de ejecución permite a Linux
proporcionar un soporte limitado para binarios compilados bajo otros
sistemas operativos de tipo Unix.

.B personality
hará que el dominio de ejecución referenciado por
.I persona
sea el nuevo dominio de ejecución del proceso en curso.
.SH "VALOR DEVUELTO"
En caso de éxito,
.I persona
es el nuevo dominio de ejecución y se devuelve la
.I persona
anterior. En caso de error, se devuelve \-1 y se pone un valor
apropiado en \fIerrno\fP.
.SH ERRORES
.TP
.B EINVAL
.I persona
no se refiere a un dominio de ejecución válido.
.PP
.SH FICHEROS
.I /usr/include/linux/personality.h
.SH "CONFORME A"
.B personality
es específico de Linux y no debería emplearse en programas que se
pretendan transportables.
\"  LocalWords:  referenciado
