.\" Copyright 1993 Giorgio Ciucci (giorgio@crcc.it)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified Tue Oct 22 17:54:56 1996 by Eric S. Raymond <esr@thyrsus.com>
.\" Translated 26 Jan 1998 by
.\" 	Vicente Pastor Gómez <VPASTORG@santandersupernet.com , vicpastor@hotmail.com>
.\" Translation revised on Tue Apr 6 1999 by Juan Piernas <piernas@ditec.um.es>
.\" Translation revised on Fri Jun 25 1999 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH SEMGET 2 "1 noviembre 1993" "Linux 0.99.13" "Manual del Programador de Linux" 
.SH NOMBRE
semget \- obtiene el identificador de un conjunto de semáforos
.SH SINOPSIS
.nf
.B
# include <sys/types.h>
.B
# include <sys/ipc.h>
.B
# include <sys/sem.h>
.fi
.sp
.BI "int semget ( key_t " key ,
.BI "int " nsems ,
.BI "int " semflg " )"
.SH DESCRIPCIÓN
La función devuelve el identificador del conjunto de semáforos asociado al valor del argumento
.IR key .
Un nuevo conjunto de 
.I nsems
semáforos se crea si
.I key
tiene el valor
.BR IPC_PRIVATE ,
o si
.I key
no vale
.BR IPC_PRIVATE ,
no hay un conjunto de semáforos asociado a
.IR key ,
y el bit
.B IPC_CREAT
vale 1 en
.I semflg
(p.ej.
.IR semflg " &"
.B IPC_CREAT
es distinto de cero).
La presencia en
.I semflg
de los campos
.B IPC_CREAT
e
.B IPC_EXCL
tiene el mismo papel, con respecto a la existencia del conjunto de semáforos,
que la presencia de
.B O_CREAT
y
.B O_EXCL
en el argumento mode de la llamada del sistema
.BR open (2):
p.ej., la función
.B semget
falla si
.I semflg
tiene a 1 tanto
.B IPC_CREAT
como
.B IPC_EXCL
y ya existe un conjunto de semáforos para
.IR key .
.PP
Acerca de la creación, los 9 bits bajos del argumento
.I semflg
definen los permisos de acceso (para el propietario, grupo y otros)
al conjunto de semáforos en el mismo formato, y con el mismo significado,
que para el parámetro de permisos de acceso en las llamadas al sistema
.BR open (2)
o
.BR creat (2)
(aunque los permisos de ejecución no son usados por el sistema, y los
de escritura, para un conjunto de semáforos, efectivamente significa permisos de modificación).

.PP
Además, durante la creación, la llamada al sistema inicializa la estructura
de datos
.B semid_ds
del conjunto de semáforos del sistema, como sigue:
.IP
Se pone el ID  de usuario efectivo del proceso que realiza la llamada en
.B sem_perm.cuid
y
.B sem_perm.uid
.
.IP
Se pone el ID de grupo efectivo del proceso que realiza la llamada en
.B sem_perm.cgid
y
.B sem_perm.gid
.
.IP
Los 9 bits más bajos de
.B sem_perm.mode
se ponen como los 9 bits más bajos de
.IR semflg .
.IP
Se pone el valor de
.IR nsems
en
.BR sem_nsems .
.IP
.B sem_otime
se pone a 0.
.IP
Se pone la hora actual en
.BR sem_ctime.
.PP
El argumento
.I nsems
puede ser
.B 0
(un comodín o valor sin importancia)
cuando la llamada del sistema no es de creación.
En otro caso
.I nsems
debe ser mayor que
.B 0
y menor o igual que el número máximo de semáforos por semid,
.RB ( SEMMSL ).
.PP
Si el conjunto de semáforos ya existe, los permisos de acceso son verificados,
y se hace una comprobación para ver si está marcado para ser destruido.
.SH "VALOR REGRESADO"
Si hubo éxito, el valor devuelto será el identificador del conjunto de
semáforos (un entero positivo), de otro modo, se devuelve
.B \-1
con
.B errno
indicando el error.
.SH ERRORES
Para un retorno fallido,
.B errno
tendrá uno de entre los siguientes valores:
.TP 11
.B EACCES
Existe un conjunto de semáforos para
.IR key ,
pero el proceso que realiza la llamada no tiene permisos de acceso al conjunto.
.TP
.B EEXIST
Existe un conjunto de semáforos para
.B key
y
.I semflg
tiene a 1 tanto
.B IPC_CREAT
como
.BR IPC_EXCL .
.TP
.B EIDRM
El conjunto de semáforos está marcado para ser borrado.
.TP
.B ENOENT
No existe ningún conjunto de semáforos para
.I key
y
.I semflg
no tiene a 1
.BR IPC_CREAT .
.TP
.B ENOMEM
Se ha de crear un conjunto de semáforos, pero el sistema no tiene suficiente
memoria para la nueva estructura de datos.
.TP
.B ENOSPC
Se ha de crear un conjunto de semáforos, pero el límite del sistema para el
número máximo de conjuntos de semáforos
.RB ( SEMMNI ),
o el número de semáforos máximo del sistema
.RB ( SEMMNS ),
sería excedido.
.SH NOTAS
.B IPC_PRIVATE
no es un campo bandera (flag), sino que es de tipo
.B key_t
.
Si este valor especial es usado para
.IR key ,
la llamada del sistema ignora todo excepto los 9 bits más bajos de
.I semflg
y crea un nuevo conjunto de semáforos (si hay éxito).
.PP
Los siguientes son límites de los recursos de los conjuntos de semáforos
que afectan a la llamada
.B semget
:
.TP 11
.B SEMMNI
Máximo total de conjuntos de semáforos para el sistema: depende de la política.
.TP
.B SEMMSL
Máximo de semáforos por semid: depende de la implementación
(500 normalmente).
.TP
.B SEMMNS
Máximo total de semáforos para el sistema: depende de la política.
Valores mayores que
.B SEMMSL * SEMMNI
lo hacen irrelevante.
.SH FALLOS
El uso de
.B IPC_PRIVATE
no inhibe el acceso de los demás procesos al conjunto de semáforos asignado.
.PP
Al igual que pasa con los ficheros, no hay una manera intrínseca para que un
proceso se asegure el acceso exclusivo a un conjunto de semáforos.
Tener a 1 tanto
.B IPC_CREAT
como
.B IPC_EXCL
en
.I semflg
solo asegura (si hay éxito) la creación de un nuevo conjunto de semáforos,
no implica acceso exclusivo a dicho conjunto.
.PP
La estructura de datos asociada con cada semáforo del conjunto no es
inicializada por la llamada del sistema.
Para inicializar estas estructuras de datos, se ha de ejecutar la subsiguiente
llamada a
.BR semctl (2)
para realizar un comando
.B SETVAL
o
.B SETALL
en el conjunto de semáforos.
.SH "CONFORME A"
SVr4, SVID.  SVr4 documenta condiciones de error adicionales EINVAL, EFBIG,
E2BIG, EAGAIN, ERANGE, EFAULT.
.SH "VÉASE TAMBIÉN"
.BR ftok (3),
.BR ipc (5),
.BR semctl (2),
.BR semop (2)
