.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sat Jul 24 21:42:42 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.\" Traducido al castellano (con permiso) por:
.\" Sebastian Desimone (chipy@argenet.com.ar) (desimone@fasta.edu.ar)
.\" Traducción revisada 25 Mayo 1998 por Carlos Costa Portela <c.c.portela@ieee.org>
.\"
.TH ASSERT 3  "19 Diciembre 1995" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
assert \- aborta el programa si la expresión es falsa.
.SH SINOPSIS
.nf
.B #include <assert.h>
.sp
.BI "void assert (int " "expression" ");"
.fi
.SH DESCRIPCIÓN
.B assert()
imprime un mensaje de error a la salida estándar y termina el programa
llamando a 
.B abort()
si
.B expression
es falsa (es decir, es igual a cero).  Esto sólo sucede cuando la macro
.B NDEBUG
está sin definir.
.SH "VALOR DEVUELTO"
No se devuelve ningún valor.
.SH "CONFORME A"
ANSI - C
.SH "FALLOS"
.B assert()
es implementada como un macro; si la expresión comprobada tiene efectos
laterales, el comportamiento del programa puede ser diferente dependiendo
de si
.B NDEBUG
está definida o no. Esto puede crear fallos indeterminados (Heisenbugs) que
no se dan cuando la depuración está activada.
.SH "VÉASE TAMBIÉN"
.BR exit "(3), " abort (3)
