.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Mon Mar 29 22:39:24 1993, David Metcalfe
.\" Modified Sat Jul 24 21:39:22 1993, Rik Faith (faith@cs.unc.edu)
.\"
.\" Traducido al castellano (con permiso) por:
.\" Sebastian Desimone (chipy@argenet.com.ar) (desimone@fasta.edu.ar)
.\" Revisado Mon Apr 21 11:21:06 1998 por:
.\" Cesar D. Lobejon (cesar@alien.mec.es)            
.TH ATOF 3  "29 Marzo 1993" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
atof \- convierte una cadena a un \fBdouble\fP.
.SH SINOPSIS
.nf
.B #include <stdlib.h>
.sp
.BI "double atof(const char *" nptr );
.fi
.SH DESCRIPCIÓN
La función \fBatof()\fP convierte la porción inicial de la cadena 
apuntada por \fInptr\fP a un double. El comportamiento es el mismo que
.sp
.RS
.B strtod(nptr, (char **)NULL);
.RE
.sp
excepto que \fBatof()\fP no detecta errores.
.SH "VALOR DEVUELTO"
El valor convertido.
.SH "CONFORME A"
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH "VÉASE TAMBIÉN"
.BR atoi "(3), " atol "(3), " strtod "(3), " strtol "(3), " strtoul (3)
