.\" @(#)bindresvport.3n	2.2 88/08/02 4.0 RPCSRC; from 1.7 88/03/14 SMI
.\" Translated on Sat Nov 13, 1999 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH BINDRESVPORT 3N  "22 noviembre 1987"
.SH NOMBRE
bindresvport \- liga un conector (socket) a un puerto IP privilegiado
.SH SINOPSIS
.nf
.B #include <sys/types.h>
.B #include <netinet/in.h>
.LP
.B int bindresvport(int sd, struct sockaddr_int \(**sin);
.fi
.SH DESCRIPCIÓN
.LP
.B bindresvport(\|)
se usa para ligar el descriptor de un conector a un puerto
.SM IP
privilegiado, es decir, un número de puerto en el intervalo 0-1023. La
rutina devuelve 0 en caso de éxito y \-1 en caso contrario, asignado a
.B errno
un valor que refleje la causa del error.
.LP
Sólo el superusuario puede realizar un enlace a un puerto privilegiado. Esta
llamada fallará para cualquier otro usuario.
