.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:38:44 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into Spanish, Mon Jan 12 1998, Gerardo Aburruzaga García
.\" <gerardo.aburruzaga@uca.es>
.\"
.TH FGETGRENT 3  "12 de Enero de 1998" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
fgetgrent \- obtiene una entrada del fichero de grupos
.SH SINOPSIS
.nf
.B #include <grp.h>
.B #include <stdio.h>
.B #include <sys/types.h>
.sp
.BI "struct group *fgetgrent(FILE *" flujo );
.fi
.SH DESCRIPCIÓN
La función 
.B fgetgrent()
devuelve un puntero a una estructura que contiene la información de
grupos que está en el fichero correspondiente a \fIflujo\fP. La
primera vez que se la llama devuelve la primera entrada; a partir de
ahí, devuelve las entradas sucesivas. El fichero correspondiente a
.I flujo
debe tener el mismo formato que \fI/etc/group\fP.
.PP
La estructura
.I group
se define en
.I <grp.h>
como sigue:
.sp
.RS
.nf
.ta 8n 16n 32n
struct group {
        char    *gr_name;        /* nombre del grupo */
        char    *gr_passwd;      /* contraseña del grupo */
        gid_t   gr_gid;          /* identificador del grupo */
        char    **gr_mem;        /* miembros del grupo */
};
.ta
.fi
.RE
.SH "VALOR DEVUELTO"
La función
.B fgetgrent()
devuelve la dirección de la estructura con información sobre los
grupos, o NULL si no hay más entradas o ha ocurrido un error.
.SH ERRORES
.TP
.B ENOMEM
No hay bastante memoria para alojar la estructura de información de grupos.
.SH "CONFORME A"
SVID 3
.SH "VÉASE TAMBIÉN"
.BR getgrnam "(3), " getgrgid "(3), " getgrent (3),
.BR setgrent "(3), " endgrent (3)
