.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Translated Sun Apr 23 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH FPUTWS 3  "25 julio 1999" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
fputws \- escribe una cadena de caracteres anchos en un flujo FILE
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "int fputws (const wchar_t *" ws ", FILE *" stream );
.fi
.SH DESCRIPCIÓN
La función \fBfputws\fP es equivalente para caracteres anchos a la función
\fBfputs\fP. Escribe la cadena de caracteres anchos que comienza en
\fIws\fP y termina en un carácter L'\\0' (sin incluir a éste), en
\fIstream\fP.
.SH "VALOR DEVUELTO"
La función \fBfputws\fP devuelve un entero no negativo si la operación ha
tenido éxito o \-1 para indicar un error.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR fputwc (3)
.SH OBSERVACIONES
El comportamiento de \fBfputws\fP depende de la categoría LC_CTYPE de la
localización actual.
.PP
En ausencia de información adicional pasada a la llamada fopen, es razonable
esperar que \fBfputws\fP realmente escriba la cadena multibyte
correspondiente a la cadena de caracteres anchos \fIws\fP.
