.\" @(#)getrpcport.3r	2.2 88/08/02 4.0 RPCSRC; from 1.12 88/02/26 SMI
.\" Translated on Sat Nov 13, 1999 by Juan Piernas <piernas@ditec.um.es>
.TH GETRPCPORT 3R "6 octubre 1987"
.SH NOMBRE
getrpcport \- devuelve un número de puerto RPC
.SH SINOPSIS
.ft B
.nf
int getrpcport(char *host, int prognum, int versnum, int proto);
.fi
.SH DESCRIPCIÓN
.IX getrpcport "" "\fLgetrpcport\fR \(em devuelve un número de puerto RPC"
.B getrpcport(\|)
devuelve el número de puerto para la versión
.I versnum
del programa RPC
.I prognum
que se está ejecutando en
.I host
y que está usando el protocolo
.IR proto .
Devuelve 0 si no puede contactar con el "portmapper" o si 
.I prognum
no está registrado. En el caso en que
.I prognum
está registrado pero no con la versión
.IR versnum ,
devolverá un número de puerto (para alguna versión del programa)
indicando que el programa está, de hecho, registrado.
La discrepancia de versiones será detectada en la primera llamada al
servicio.
