.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 19:11:11 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated 27 Feb 1998 by Vicente Pastor Gómez <VPASTORG@santandersupernet.com , vicpastor@hotmail.com>
.TH INFNAN 3  "2 Jun 1993" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
infnan \- maneja un resultado infinito o no-numérico (not-a-number, NaN)
.SH SINOPSIS
.nf
.B #include <math.h>
.sp
.BI "double infnan(int " error );
.fi
.SH DESCRIPCIÓN
La función \fBinfnan()\fP devuelve un valor manejable para un valor infinito
o no-numérico (NaN). El valor de \fIerror\fP puede ser ERANGE para representar
infinito, o cualquier otro valor para NaN. \fIerrno\fP también se actualiza.
.SH "VALOR REGRESADO"
Si \fIerror\fP es ERANGE (infinito), se devuelve HUGE_VAL.
.PP
Si \fIerror\fP es -ERANGE (-infinito), se devuelve -HUGE_VAL.
.PP
Si \fIerror\fP es cualquier otra cosas, se devuelve NAN.
.SH "ERRORES"
.TP
.B ERANGE
El valor de \fIerror\fP es infinito positivo o negativo.
.TP
.B EDOM
El valor de \fIerror\fP es no-numérico (NaN).
.SH "CONFORME A"
BSD 4.3

