.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o 
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH ISWALNUM 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
iswalnum \- comprueba si un carácter ancho es alfanumérico
.SH SINOPSIS
.nf
.B #include <wctype.h>
.sp
.BI "int iswalnum (wint_t " wc );
.fi
.SH DESCRIPCIÓN
La función \fBiswalnum\fP es la equivalente para caracteres anchos 
a la función \fBisalnum\fP. Comprueba si \fIwc\fP es un carácter 
ancho perteneciente a la clase de caracteres anchos "alnum".
.PP
La clase de caracteres anchos "alnum" es una subclase de la 
clase de caracteres anchos "graph", y por tanto también una 
subclase de la clase de caracteres anchos "print".
.PP
Al ser una subclase de la clase de caracteres anchos "print", la 
clase de caracteres anchos "alnum" es disjunta de la clase 
de caracteres anchos "cntrl".
.PP
Al ser una subclase de la clase de caracteres anchos "graph", la clase de
caracteres anchos "alnum" es disjuta de la clase de caracteres anchos
"space" y de su subclase "blank".
.PP
La clase de caracteres anchos "alnum" es disjunta de la clase
de caracteres anchos "punct".
.PP
La clase de caracteres anchos "alnum" es la unión de las clases 
de caracteres anchos "alpha" y "digit". Como tal, también contiene el
conjunto de caracteres "xdigit".
.PP
La clase de caracteres anchos "alnum" siempre contiene al menos las 
letras desde la 'A' a la 'Z', 'a' a la 'z' y los dígitos del '0' al '9'.
.SH "VALOR DEVUELTO"
La función \fBiswalnum\fP devuelve un valor no nulo
si  \fIwc\fP es una carácter ancho perteneciente a la clase 
de caracteres anchos "alnum". En otro caso devuelve cero.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR isalnum "(3), " iswctype (3)
.SH NOTAS
El comportamiento de \fBiswalnum\fP depende de la categoría LC_CTYPE 
de la localización actual.
