.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   ISO/IEC 9899:1999
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/onl
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH ISWPRINT 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
iswprint \- comprueba si un carácter ancho es imprimible
.SH SINOPSIS
.nf
.B #include <wctype.h>
.sp
.BI "int iswprint (wint_t " wc );
.fi
.SH DESCRIPCION
La función \fBiswprint\fP es la equivalente para caracteres anchos a
la función \fBisprint\fP. Verifica si \fIwc\fP es un carácter ancho
perteneciente a la clase de caracteres anchos "print".
.PP
La clase de caracteres anchos "print" es disjunta de la clase 
de caracteres anchos "cntrl".
.PP
La clase de caracteres anchos "print" contiene la clase
de caracteres anchos "graph".
.SH "VALOR DEVUELTO"
La función \fBiswprint\fP devuelve un valor no nulo
si \fIwc\fP es una carácter ancho perteneciente a la clase
de caracteres anchos "print". En otro caso devuelve cero.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR isprint "(3), " iswctype (3)
.SH NOTAS
El comportamiento de \fBiswprint\fP depende de la categoría LC_CTYPE
de la localización actual.
