.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:43:46 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into Spanish Thu Mar  5 15:51:13 CET 1998 by Gerardo
.\" Aburruzaga García <gerardo.aburruzaga@uca.es>
.\"
.TH PUTPWENT 3  "5 Marzo 1998" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
putpwent \- escribe una entrada en un fichero de usuarios
.SH SINOPSIS
.nf
.B #include <pwd.h>
.B #include <stdio.h>
.B #include <sys/types.h>
.sp
.BI "int putpwent(const struct passwd *" p ", FILE *" flujo );
.fi
.SH DESCRIPCIÓN
La función \fBputpwent()\fP escribe una entrada de usuario de la estructura
\fIp\fP en el fichero asociado con \fIflujo\fP.
.PP
La estructura \fIpasswd\fP se define en \fI<pwd.h>\fP así:
.sp
.RS
.nf
.ta 8n 16n 32n
struct passwd {
        char    *pw_name;	/* nombre de usuario */
        char    *pw_passwd;	/* contraseña cifrada */
        uid_t   pw_uid;		/* UID */
        gid_t   pw_gid;		/* GID */
        char    *pw_gecos;      /* nombre real */
        char    *pw_dir;  	/* directorio de casa */
        char    *pw_shell;      /* programa shell */
};
.ta
.fi
.RE
.SH "VALOR DEVUELTO"
La función \fBputpwent()\fP devuelve 0 en caso de éxito, ó \-1 si
ocurre un error.
.SH ERRORES
.TP
.B EINVAL
Argumento inválido (NULL).
.SH "CONFORME A"
SVID 3
.SH "VÉASE TAMBIÉN"
.BR fgetpwent "(3), " getpwent "(3), " setpwent (3),
.BR endpwent "(3), " getpwnam "(3), " getpwuid "(3), " getpw (3)
