.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Translated Sun Apr 23 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH PUTWCHAR 3  "25 julio 1999" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
putwchar \- escribe un carácter ancho en la salida estándar
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wint_t putwchar (wchar_t " wc );
.fi
.SH DESCRIPCIÓN
La función \fBputwchar\fP es equivalente para caracteres anchos a la función
\fBputchar\fP. Escribe el carácter ancho \fIwc\fP en \fBstdout\fP.
Si \fIferror(stdout)\fP es cierto, se devuelve WEOF. Si se produce un error
en la conversión de caracteres anchos, se asigna a \fBerrno\fP el valor
\fBEILSEQ\fP y se devuelve WEOF.
En otro caso, se devuelve \fIwc\fP.
.SH "VALOR DEVUELTO"
La función \fBputwchar\fP devuelve \fIwc\fP si no se ha producido ningún
error, o WEOF para indicar un error.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR fputwc (3)
.SH OBSERVACIONES
El comportamiento de \fBputwchar\fP depende de la categoría LC_CTYPE de la
localización actual.
.PP
Es razonable esperar que \fBputwchar\fP escriba realmente la secuencia
multibyte correspondiente al carácter ancho \fIwc\fP.
