.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sat Jul 24 18:16:02 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into Spanish Mon Mar  9 10:19:55 CET 1998 by Gerardo
.\" Aburruzaga García <gerardo.aburruzaga@uca.es>
.\"
.TH SLEEP 3  "9 Marzo 1998" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
sleep \- Duerme durante el número de segundos especificado
.SH SINOPSIS
.nf
.B #include <unistd.h>
.sp
.BI "unsigned int sleep(unsigned int " "segundos" ");"
.fi
.SH DESCRIPCIÓN
.B sleep()
hace que el proceso en curso se duerma hasta que hayan transcurrido
.I segundos
segundos o hasta que llegue una señal que sea tenida en cuenta.
.SH "VALOR DEVUELTO"
Cero si el tiempo pedido ha pasado, o el número de segundos que quedan
de sueño.
.SH "CONFORME A"
POSIX.1
.SH "FALLOS"
.B sleep()
puede estar implementada con
.BR SIGALRM ;
mezclar llamadas a
.B alarm()
y a
.B sleep() 
es una mala idea.
.PP
Utilizar
.B longjmp()
desde un manejador de señales o modificar el manejo de
.B SIGALRM
mientras se está durmiento, producirá resultados no definidos.
.SH "VÉASE TAMBIÉN"
.BR signal "(2), " alarm (2)
