.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sun Jul 25 10:40:44 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into Spanish Wed Mar 11 09:36:47 CET 1998 by Gerardo
.\" Aburruzaga García <gerardo.aburruzaga@uca.es>
.\" Translation revised April 27 1998 by Juan Piernas <piernas@dif.um.es>
.\"
.TH STRCOLL 3  "12 Abril 1993" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
strcoll \- compara dos cadenas según la localización en curso
.SH SINOPSIS
.nf
.B #include <string.h>
.sp
.BI "int strcoll(const char *" s1 ", const char *" s2 );
.fi
.SH DESCRIPCIÓN
La función \fBstrcoll()\fP compara las dos cadenas de caracteres \fIs1\fP y
\fIs2\fP.  Devuelve un entero menor, igual o mayor que cero si se
encuentra que \fIs1\fP es menor, igual o mayor que \fIs2\fP.  La
comparación se basa en la interpretación apropiada de los caracteres de las
cadenas según la actual localización del programa para la categoría
\fILC_COLLATE\fP.  (Vea \fBsetlocale\fP(3)).
.SH "VALOR DEVUELTO"
La función \fBstrcoll()\fP devuelve un entero menor, igual o mayor que
cero si se encuentra, respectivamente, que \fIs1\fP es menor, igual o
mayor que \fIs2\fP, donde ambas cadenas se interpretan de la forma
adecuada para la localización en curso.
.SH "CONFORME A"
SVID 3, BSD 4.3, ISO 9899
.SH OBSERVACIONES
En las localizaciones \fI"POSIX"\fP o \fI"C"\fP, \fBstrcoll()\fP es
equivalente a \fBstrcmp()\fP.
.SH "VÉASE TAMBIÉN"
.BR bcmp "(3), " memcmp "(3), " strcasecmp "(3), " strcmp (3),
.BR strxfrm "(3), " setlocale (3)
