.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:57:50 1993 by Rik Faith (faith@cs.unc.edu)
.TH STRSPN 3  "12 de Abril de 1993" "" "Manual del Programador de Linux"
.SH NOMBRE
strspn, strcspn \- busca un conjunto de caracteres en una cadena
.SH SINOPSIS
.nf
.B #include <string.h>
.sp
.BI "size_t strspn(const char *" s ", const char *" acepta );
.sp
.BI "size_t strcspn(const char *" s ", const char *" rechaza );
.fi
.SH DESCRIPCIÓN
La función \fBstrspn()\fP calcula la longitud del segmento inicial de \fIs\fP
que consta únicamente de caracteres en \fIacepta\fP.
.PP
La función \fBstrcspn()\fP calcula la longitud del segmento inicial de \fIs\fP
que consta únicamente de caracteres que no aparecen en \fIrechaza\fP.
.SH "VALOR DEVUELTO"
La función \fBstrspn()\fP devuelve el número de caracteres del segmento inicial de
\fIs\fP que contiene sólo caracteres perteneciantes a \fIacepta\fP.
.PP
La función \fBstrcspn()\fP devuelve el número de caracteres del segmento inicial de
\fIs\fP que consta únicamente de caracteres que no están en \fIrechaza\fP.
.SH "CONFORME A"
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH "VÉASE TAMBIÉN"
.BR index "(3), " memchr "(3), " rindex "(3), " strchr (3),
.BR strpbrk "(3), " strsep "(3), " strstr "(3), " strtok (3)
