.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:48:42 1993 by Rik Faith (faith@cs.unc.edu)
.\" Translated into Spanish Thu Mar 12 16:02:28 CET 1998 by Gerardo
.\" Aburruzaga García <gerardo.aburruzaga@uca.es>
.\"
.TH TELLDIR 3  "12 Marzo 1998" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
telldir \- devuelve la posición actual en un flujo directorio.
.SH SINOPSIS
.nf
.B #include <dirent.h>
.sp
.BI "off_t telldir(DIR *" dir );
.fi
.SH DESCRIPCIÓN
La función \fBtelldir()\fP devuelve la  posición actual asociada al
flujo de directorio \fIdir\fP.
.SH "VALOR DEVUELTO"
La función \fBtelldir()\fP devuelve la posición en curso en el flujo
de directorio ó \-1 si ocurre un error.
.SH "ERRORES"
.TP
.B EBADF
Descriptor de flujo de directorio inválido \fIdir\fP.
.SH "CONFORME A"
BSD 4.3
.SH "VÉASE TAMBIÉN"
.BR opendir "(3), " readdir "(3), " closedir "(3), " rewinddir (3),
.BR seekdir "(3), " scandir (3)
