.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sun Jul 25 11:01:58 1993 by Rik Faith (faith@cs.unc.edu)
.\" Traducción por Urko Lusa <ulusa@lacueva.ddns.org> 19980323
.TH TZSET 3  "2 de julio de 1993" "BSD" "Manual del programador de Linux"
.SH NOMBRE
tzset \- inicializa la información de conversión horaria
.SH SINOPSIS
.nf
.B #include <time.h>
.sp
.B void tzset (void);
.sp
.BI "extern char *" tzname [2]
.fi
.SH DESCRIPCIÓN
La función \fBtzset()\fP inicializa la variable \fItzname\fP a partir de la
variable de entorno TZ. Esta función es invocada automáticamente por otras
funciones conversoras de tiempo que dependen de la zona horaria.
.PP
Si la variable TZ no está presente en el entorno, la variable \fItzname\fP
se inicializa con la mejor aproximación de la hora local, tal como se
especifica en el fichero \fI/usr/lib/zoneinfo/localtime\fP, cuyo formato se
detalla en
.BR tzfile (5).
.PP
Si la variable TZ está presente en el entorno, pero su valor es NULL o no
puede ser interpretado usando ninguno de los formatos especificados abajo,
se usa el Tiempo Coordinado Universal (UTC).
.PP
La variable TZ puede tener tres formatos. El primero se usa cuando no
hay horario de ahorro energético en la zona horaria local:
.sp
.RS
.I nzh desfase
.RE
.sp
La cadena \fInzh\fP especifica el nombre de la zona horaria, y debe
componerse de tres o más caracteres alfabéticos. La cadena \fIdesfase\fP
sigue inmediatamente después de \fInzh\fP y especifica el tiempo a añadir a
la hora local para obtener el Tiempo Coordinado Universal (UTC). El valor de
\fIdesfase\fP es positivo si la hora local está al oeste del meridiano de
Greenwich, y negativo si está al este. La hora debe estar entre 0 y 24, y
los minutos y segundos entre 0 y 59.
.PP
El segundo formato se usa cuando hay horario de ahorro energético:
.sp
.RS
.I nzh desfase hae [desfase],inicio[/hora],fin[/hora]
.RE
.sp
No hay espacios en la especificación. El \fInzh\fP y el \fIdesfase\fP
iniciales especifican la zona horaria estándar tal como se describe arriba.
Las cadenas \fIhae\fP y \fIdesfase\fP especifican el nombre y desfase para
el correspondiente horario de ahorro energético de la zona. Si se omite el
desfase, se asume el valor de una hora por delante de la hora estándar.
.PP
El campo \fIinicio\fP especifica cuándo entra en vigor el horario de ahorro
energético, y el campo \fIfin\fP cuándo se vuelve al horario estándar. Estos
campos pueden tener los siguientes formatos:
.TP
J\fIn\fP
Especifica el día juliano, siendo \fIn\fP entre 1 y 365. El 29 de febrero
nunca se cuenta, ni siquiera en los años bisiestos.
.TP 
.I n
Especifica el día juliano, siendo \fIn\fP entre 1 y 365. El 29 de febrero se
cuenta en los años bisiestos.
.TP 
M\fIm\fP.\fIs\fP.\fId\fP
Especifica el día \fId\fP (0 <= \fId\fP <= 6) de la semana \fIs\fP (1 <=
\fIs\fP <= 5) del mes \fIm\fP (1 <= \fIm\fP <= 12). La semana 1 es la
primera semana en la que ocurre el día \fId\fP, y la semana 5 es la última
en el que ocurre el día \fId\fP. El día 0 es un domingo.
.PP
Los campos \fIhora\fP especifican cuándo (en el horario local actualmente en
vigor) ocurre el cambio al otro horario. Si se omite, el valor por defecto
es 02:00:00.
.PP
El tercer formato especifica que la información de la zona horaria debe
leerse de un fichero:
.sp
.RS
:[fichero]
.RE
.sp
Si se omite la especificación de fichero \fIfichero\fP, la información de la
zona horaria se lee de \fI/usr/lib/zoneinfo/localtime\fP, que está en
formato
.BR tzfile (5).
Si se proporciona \fIfichero\fP, especifica otro fichero de formato
.BR tzfile (5)
del que leer la información de la zona horaria. Si \fIfichero\fP no comienza
con `/', la especificación de fichero es relativa al directorio de
conversión horaria del sistema \fI/usr/lib/zoneinfo\fP.
.SH FICHEROS
.nf
/usr/lib/zoneinfo             directorio de zonas horarias
/usr/lib/zoneinfo/localtime   fichero de horario local
/usr/lib/zoneinfo/posixrules  reglas para TZ estilo POSIX
.fi
.SH "CONFORME A"
SVID 3, POSIX, BSD 4.3
.SH "VÉASE TAMBIÉN"
.BR date "(1), " gettimeofday "(2), " time "(2), " ctime (3),
.BR getenv "(3), " tzfile (5) 
