.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1995 Jim Van Zandt
.\" From jrv@vanzandt.mv.com Mon Sep  4 21:11:50 1995
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Corrections, 961108, meem@sherilyn.wustl.edu
.\"
.\" "
.TH UNDOCUMENTED 3 "25-Agosto-1995" "Linux 1.3.15" "Manual del Programador de Linux"
.SH NOMBRE
none \- funciones de biblioteca no documentadas
.SH SINOPSIS
Funciones de biblioteca no documentadas
.SH DESCRIPCIÓN
Esta página man cita aquellas funciones de biblioteca que, si bien están implementadas en las bibliotecas estándar, no están todavía documentadas en las páginas man.
.SH SOLICITUDES
Si tienes información sobre estas funciones, échale un vistazo al código fuente, escribe una página man (siguiendo el estilo de las otras páginas de la sección 3 del manual), y envíaselas
.B aeb@cwi.nl
para incluirlas en la próxima revisión del manual.
.SH "LA LISTA"
des_setparity
dn_skipname
ecb_crypt
encrypt
endnetgrent
endrpcent
endutent
fcrypt
fp_nquery
fp_query
fp_resstat
get_myaddress
getnetgrent
getnetname
getpublickey
getrpcbyname
getrpcbynumber
getrpcent
getrpcport
getsecretkey
h_errlist
host2netname
hostalias
inet_nsap_addr
inet_nsap_ntoa
init_des
innetgr
key_decryptsession
key_encryptsession
key_gendes
key_setsecret
libc_nls_init
lockf
mcheck
memalign
mstats
mtrace
netname2host
netname2user
nlist
obstack_free
p_cdname
p_cdnname
p_class
p_fqname
p_option
p_query
p_rr
p_time
p_type
passwd2des
pmap_getmaps
pmap_getport
pmap_rmtcall
pmap_set
pmap_unset
putlong
putshort
rcmd
re_compile_fastmap
re_compile_pattern
re_match
re_match_2
re_rx_search
re_search
re_search_2
re_set_registers
re_set_syntax
registerrpc
res_send_setqhook
res_send_setrhook
rexec
rresvport
rtime
ruserok
ruserpass
setfileno
sethostfile
setkey
setlogmask
setnetgrent
setrpcent
svc_exit
svc_getreq
svc_getreqset
svc_register
svc_run
svc_sendreply
svc_unregister
svcerr_auth
svcerr_decode
svcerr_noproc
svcerr_noprog
svcerr_progvers
svcerr_systemerr
svcerr_weakauth
svcfd_create
svcraw_create
svctcp_create
svcudp_bufcreate
svcudp_create
svcudp_enablecache
syscall
tell
timegm
tr_break
tzsetwall
ufc_dofinalperm
ufc_doit
user2netname
valloc
vsyslog
xdecrypt
xdr_accepted_reply
xdr_array
xdr_authdes_cred
xdr_authdes_verf
xdr_authunix_parms
xdr_bool
xdr_bytes
xdr_callhdr
xdr_callmsg
xdr_char
xdr_cryptkeyarg
xdr_cryptkeyres
xdr_datum
xdr_des_block
xdr_domainname
xdr_double
xdr_enum
xdr_float
xdr_free
xdr_getcredres
xdr_int
xdr_keybuf
xdr_keystatus
xdr_long
xdr_mapname
xdr_netnamestr
xdr_netobj
xdr_opaque
xdr_opaque_auth
xdr_passwd
xdr_peername
xdr_pmap
xdr_pmaplist
xdr_pointer
xdr_reference
xdr_rejected_reply
xdr_replymsg
xdr_rmtcall_args
xdr_rmtcallres
xdr_short
xdr_string
xdr_u_char
xdr_u_int
xdr_u_long
xdr_u_short
xdr_union
xdr_unixcred
xdr_vector
xdr_void
xdr_wrapstring
xdr_yp_buf
xdr_yp_inaddr
xdr_ypbind_binding
xdr_ypbind_resp
xdr_ypbind_resptype
xdr_ypbind_setdom
xdr_ypdelete_args
xdr_ypmaplist
xdr_ypmaplist_str
xdr_yppasswd
xdr_ypreq_key
xdr_ypreq_nokey
xdr_ypresp_all
xdr_ypresp_all_seq
xdr_ypresp_key_val
xdr_ypresp_maplist
xdr_ypresp_master
xdr_ypresp_order
xdr_ypresp_val
xdr_ypstat
xdr_ypupdate_args
xdrmem_create
xdrrec_create
xdrrec_endofrecord
xdrrec_eof
xdrrec_skiprecord
xdrstdio_create
xencrypt
xprt_register
xprt_unregister
yp_all
yp_bind
yp_first
yp_get_default_domain
yp_maplist
yp_master
yp_match
yp_next
yp_order
yp_unbind
yp_update
yperr_string
ypprot_err


