.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/onl
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WCSDUP 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
wcsdup \- duplica una cadena de caracteres anchos
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsdup (const wchar_t *" s );
.fi
.SH DESCRIPCION
La función \fBwcsdup\fP es el equivalente de caracteres anchos de
la función \fBstrdup\fP. Ubica y devuelve una nueva cadena de 
caracteres anchos cuyo contenido inicial es un duplicado de 
la la cadena de caracteres anchos apuntada por \fIs\fP.
.PP
La memoria asignada a la nueva cadena de caracters se 
obtiene con \fBmalloc\fP(3) y se puede liberar con \fBfree\fP(3).
.SH "VALOR DEVUELTO"
La función \fBwcsdup\fP devuelve un puntero a la nueva 
la cadena de caracteres anchos o NULL si no hay suficiente
memoria disponible.
.SH "CONFORME A"
Esta función es una extensión GNU.
.SH "VÉASE TAMBIÉN"
.BR strdup "(3), " wcscpy (3)
