.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/onl
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WCSNCMP 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
wcsncmp \- compara dos cadenas de caracteres anchos de tamaño fijo
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "int wcsncmp (const wchar_t *" s1 ", const wchar_t *" s2 ", size_t " n );
.fi
.SH DESCRIPCION
La función \fBwcsncmp\fP es el equivalente de caracteres anchos de
la función \fBstrncmp\fP.
Compara la cadena de caracteres anchos a la que apunta
\fIs1\fP y la cadena de caracteres anchos
apuntada por \fIs2\fP, pero a lo sumo \fIn\fP caracteres anchos
por cadena. En cada cadena, la comparación se extiende sólo hasta 
la primera ocurrencia de una caracter L'\\0' si existe.
.SH "VALOR DEVUELTO"
La función \fBwcscmp\fP devuelve cero si las cadena de caracteres anchos,
truncadas a lo sumo a \fIn\fP caracteres anchos, \fIs1\fP y \fIs2\fP son 
iguales.
Devuelve un entero positivo si en la primera posición diferente 
\fIi\fP (\fIi\fP < \fIn\fP) el correspondiente carácter ancho
\fIs1[i]\fP es mayor que \fIs2[i]\fP.
Devuelve un entero negativo si en la pimera posición diferente 
\fIi\fP (\fIi\fP < \fIn\fP) el correspondiente carácter ancho
\fIs1[i]\fP es menor que \fIs2[i]\fP.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR strncmp "(3), " wcsncasecmp (3)
