.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/onl
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WCSCAT 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
wcscat \- busca un carácter ancho en una cadena de caracteres anchos
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcsrchr (const wchar_t *" wcs ", wchar_t " wc );
.fi
.SH DESCRIPCION
La función \fBwcsrchr\fP es el equivalente de caracteres anchos de
la función \fBstrrchr\fP. Busca la última ocurrencia de \fIwc\fP  en
la cadena de caracteres anchos apuntada por \fIwcs\fP.
.SH "VALOR DEVUELTO"
La función \fBwcsrchr\fP devuelve un puntero a la última
ocurrencia de \fIwc\fP en la cadena de caracteres anchos
apuntada por \fIwcs\fP o NULL si \fIwc\fP no aparece en la cadena.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR strrchr "(3), " wcschr (3)
