.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/onl
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WCSSPN 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
wcsspn \- avanza en una cadena de caracteres anchos,
saltando cualquiera carácter perteneciente a un conjunto de caracteres
anchos dado
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wcsspn (const wchar_t *" wcs ", const wchar_t *" accept );
.fi
.SH DESCRIPCION
La función \fBwcsspn\fP es el equivalente de caracteres anchos de
la función \fBstrspn\fP. Determina la longitud del segmento
inicial más largo de \fIwcs\fP que está formado completamente
por caracteres anchos listados en \fIaccept\fP. En otras
palabras, busca la primera ocurrencia en la cadena de caracteres
anchos \fIwcs\fP de cualquiera de los caracteres que no están en la
cadena de caracteres anchos \fIaccept\fP.
.SH "VALOR DEVUELTO"
La función \fBwcsspn\fP devuelve el número de caracteres
anchos del segmento inicial más largo de la cadena \fIwcs\fP
que consista por completo en caracteres anchos listados en
\fIaccept\fP. En otras palabras, devuelve la posición de la primera
aparición en la cadena de caracteres anchos \fIwcs\fP de cualquiera de
los carácter no contenidos en la cadena de caracteres anchos \fIaccept\fP,
o \fIwcslen(wcs)\fP si no hay ninguno.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR strspn "(3), " wcscspn (3)
