.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" Traducida por Pedro Pablo Fábrega <pfabrega@arrakis.es>
.\" Esto es documentación libre; puede redistribuirla y/o
.\" modificarla bajo los términos de la Licencia Pública General GNU
.\" publicada por la Free Software Foundation; bien la versión 2 de
.\" la Licencia o (a su elección) cualquier versión posterior.
.\"
.\" Referencias consultadas:
.\"   código fuente y manual de glibc-2 GNU
.\"   referencia de la bibliote C Dinkumware http://www.dinkumware.com/
.\"   Especificaciones Single Unix de OpenGroup http://www.UNIX-systems.org/onl
.\"
.\" Translation revised Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WCWIDTH 3  "25 julio 1999" "GNU" "Manual del Programador Linux"
.SH NOMBRE
wcwidth \- determina las columnas necesarias para un carácter ancho
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "int wcwidth (wint_t " c );
.fi
.SH DESCRIPCIÓN
La función \fBwcwidth\fP devuelve el número de columnas
necesarias para representar el carácter ancho \fIc\fP.
Si \fIc\fP es una carácter ancho imprimible, el valor es 
al menos 1. Si \fIc\fP es L'\\0' el valor es cero. 
En otro caso devuelve -1.
.SH "VALOR DEVUELTO"
La función \fBwcwidth\fP devuelve el número de posiciones de columna para
\fIc\fP.
.SH "CONFORME A"
UNIX98
.SH "VÉASE TAMBIÉN"
.BR wcswidth "(3), " iswprint (3)
.SH NOTAS
El comportamiento de \fBwcwidth\fP depende de la categoría LC_CTYPE
de la localización actual.
