.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"
.\" Translated on Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WMEMCMP 3  "25 julio 1999" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
wmemcmp \- compara dos vectores de caracteres anchos
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "int wmemcmp (const wchar_t *" s1 ", const wchar_t *" s2 ", size_t " n );
.fi
.SH DESCRIPCIÓN
La función \fBwmemcmp\fP es equivalente para caracteres anchos a la función
\fBmemcmp\fP. Compara los \fIn\fP primeros caracteres anchos de \fIs1\fP
y los \fIn\fP primeros caracteres anchos de \fIs2\fP.
.SH "VALOR DEVUELTO"
La función \fBwmemcmp\fP devuelve cero si los arrays
\fIs1\fP y \fIs2\fP de \fIn\fP caracteres anchos son iguales. Devuelve un
entero mayor que 0 si en la primera posición distinta
\fIi\fP (\fIi\fP < \fIn\fP), el correpondiente carácter ancho \fIs1[i]\fP es
mayor que \fIs2[i]\fP. Devuelve un entero menor que 0 si en la primera
posición distinta \fIi\fP (\fIi\fP < \fIn\fP), el carácter ancho
correspondiente \fIs1[i]\fP es menor que \fIs2[i]\fP.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR memcmp "(3), " wcscmp (3)
