.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Translated on Wed Aug  2 2000 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WMEMMOVE 3  "25 julio 1999" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
wmemmove \- copia un vector de caracteres anchos
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemmove (wchar_t *" dest ", const wchar_t *" src ", size_t " n );
.fi
.SH DESCRIPCIÓN
La función \fBwmemmove\fP es equivalente para caracteres anchos a la función
\fBmemmove\fP. Copia \fIn\fP caracteres anchos del vector
\fIsrc\fP al vector \fIdest\fP. Los vectores se pueden solapar.
.PP
El programador debe asegurar que hay espacio para al menos \fIn\fP
caracteres anchos en \fIdest\fP.
.SH "VALOR DEVUELTO"
\fBwmemmove\fP devuelve \fIdest\fP.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR memmove "(3), " wmemcpy (3)
