.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single Unix specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" Translated on Sat Nov 13, 1999 by Juan Piernas <piernas@ditec.um.es>
.\"
.TH WMEMSET 3  "25 julio 1999" "GNU" "Manual del Programador de Linux"
.SH NOMBRE
wmemset \- rellena un array de caracteres anchos con un carácter ancho
constate.
.SH SINOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemset (wchar_t *" wcs ", wchar_t " wc ", size_t " n );
.fi
.SH DESCRIPCIÓN
La función \fBwmemset\fP es equivalente a la función \fBmemset\fP, pero para
caracteres anchos. Rellena el array de \fIn\fP caracteres anchos que
comienza en \fIwcs\fP con \fIn\fP copias del carácter ancho \fIwc\fP.
.SH "VALOR DEVUELTO"
\fBwmemset\fP devuelve \fIwcs\fP.
.SH "CONFORME A"
ISO/ANSI C, UNIX98
.SH "VÉASE TAMBIÉN"
.BR memset (3)
