#!/bin/bash
CODE=`file $1|cut -d: -f2`
if [ "$CODE" = " ISO-8859 text" ]
then
   iconv -t utf-8 -f latin1 -o tmp $1;
   mv tmp $1;
   echo 'File converted successfully'
else 
   echo 'Error: Text is not ISO-8859'
fi
   

