#!/bin/bash
CODE=`file $1|cut -d: -f2`
if [ "$CODE" = " UTF-8 Unicode text" ]
then
   iconv -f utf-8 -t latin1 -o tmp $1;
   mv tmp $1;
   echo 'File converted successfully'
else 
   echo 'Error: Text is not UTF-8'
fi
   

