.\" Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\" Translated into Spanish on Wed Jul 22 1998 by Gerardo Aburruzaga
.\" García <gerardo@cica.es>
.\"
.TH CTRLALTDEL 8 "25 Octubre 1993" "Linux 1.2" "Manual del Programador de Linux"
.SH NOMBRE
ctrlaltdel \- establece la función de la combinación Ctrl-Alt-Supr
.SH SINOPSIS
.BR "ctrlaltdel hard" " | " soft
.SH DESCRIPCIÓN
Examinando el código en
.IR linux/kernel/sys.c ,
está claro que la secuencia Ctrl-Alt-Supr puede realizar dos funciones
distintas soportadas; un rearranque
.IR  duro ,
que rearranca inmediatamente el computador sin llamar a
.BR sync (2)
y sin ninguna otra preparación, y un rearranque
.IR blando ,
que envía la señal SIGINT (interrumpir) al proceso
.B init
(éste es siempre el proceso con PID 1). Si se emplea esta opción, el
programa 
.B init (8)
debe admitir esta característica. Puesto que ahora hay varios programas
.B init (8)
en la comunidad Linux, haga el favor de consultar la documentación
para la versión que Ud. esté utilizando actualmente.

.B ctrlaltdel
se emplea usualmente en el fichero
.I /etc/rc.local
o similar.
.SH FICHEROS
.I /etc/rc.local
.SH "VÉASE TAMBIÉN"
.BR simpleinit (8),
.BR init (8)
.SH AUTOR
Peter Orbaek (poe@daimi.aau.dk)
