.\" Copyright 1992,1993,1994 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\" 
.\" Translated into Spanish on Fri Jul 24 1998 by Gerardo Aburruzaga
.\" García <gerardo@cica.es>
.\"
.TH FRAG 8 "8 Enero 1994" "Linux 0.99" "Manual del Programador de Linux"
.SH NOMBRE
frag \- comprobador simple de fragmentación
.SH SINOPSIS
.B /usr/sbin/frag
.B "[ \-s [ \-s ]]"
nombre-fichero ...
.SH DESCRIPCIÓN
.B frag
mostrará la fragmentación del sistema de ficheros en un
.I nombre-fichero 
especificado.
Si el
.I nombre-fichero
es un directorio,
.B frag
descenderá recursivamente por él.
.SH OPCIONES
.TP
.B \-s
Silencioso (puede ponerse 1 ó 2 veces). 
El primer
.B \-s
elimina las estadísticas de fichero a fichero, y sólo muestra los
directorios examinados y un resumen. El segundo
.B \-s
elimina la impresión de los directorios, y sólo muestra un
sumario. Esta opción es útil cuando 
.B frag
se emplea sobre un directorio.
.SH "VÉASE TAMBIÉN"
.BR mkfs (8),
.BR fsck (8),
.BR mkefs (8),
.BR efsck (8)
.SH FALLOS
.B frag
se quedará atrapado en un bucle infinito en el sistema de ficheros /proc.
.SH AUTORES
V1.0 por Werner Almesberger
.br
V1.1 por Steffen Zahn: añadido del recorrido recursivo de directorios
.br
V1.2 por Rob Hooft: añadido de la cuenta de agujeros
.br
V1.3 por Steffen Zahn: no tener en cuenta enlaces simbólicos,
no cruzar los límites de sistemas de ficheros, obtención del tamaño de
bloque del sistema de ficheros en tiempo de ejecución.
