.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\" Translated 5 Oct 1998 by Roberto Rodríguez Fernández (rrf@apdo.com)
.TH IPCRM 8 "9 Octubre 1993" "Linux 0.99" "Manual del Programador de Linux"
.SH NOMBRE
ipcrm \- eliminación de recursos ipc.
.SH SIPNOSIS
.BI "ipcrm [ shm | msg | sem ] " id
.SH DESCRIPCIÓN
.B ipcrm
borrará el recurso especificado por 
.IR id .
.SH VÉASE TAMBIÉN
.BR ipcs (8)
.SH AUTOR
krishna balasubramanian (balasub@cis.ohio-state.edu)
