.\" -*- nroff -*-
.\" Translated into Spanish on Fri March 5, 1999 by
.\" 	Juan Piernas Cánovas <piernas@ditec.um.es>
.TH mkpv 8 "" raidtools-0.90
.SH NONMBRE
mkpv \- crea PV's
.SH SINOPSIS
\fBmkpv\fR [--configfile] [--version] [--force]
	     [--upgrade] [-acvfuv] </dev/md?>+


.SH DESCRIPCIÓN
\fBmkpv\fR configura varios dispositivo de bloques en un único PV.

Dése cuenta que la inicialización de dispositivos PV \fBdestruye todos los
datos de los dispositivos constituyentes\fR.

.SH OPCIONS
.IP "\fB-c\fP, \fB\-\-configfile\fP \fInombrefichero\fR"
Usa \fInombrefichero\fR como fichero de configuración (por defecto se
usa \fB/etc/raidtab\fR).

.IP "\fB\-f\fP, \fB\-\-force\fP"
Inicializa los dispositivos constituyentes, incluso aunque ya parezcan tener
datos.

.IP "\fB\-h\fP, \fB\-\-help\fP"
Muestra un breve mensaje de uso y a continuación termina.

.IP "\fB\-V\fP, \fB\-\-version\fP"
Muestra un breve mensaje de versión y a continuación termina.

.SH NOTAS

El paquete raidtools deriva de los paquetes md-tools y raidtools,
que originalmente fueron escritos por Marc Zyngier, Miguel de Icaza,
Gadi Oxman, Bradley Ward Allen e Ingo Molnar.

.SH AUTOR
Ingo Molnar

.SH FALLOS (BUGS)
Probablemente muchos.

.SH VÉASE TAMBIÉN
.IR raidtab (5),
.IR ckraid (8),
.IR raidadd (8)
