.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.\"
.\" Translated into Spanish on Sun Aug 23 1998 by Gerardo Aburruzaga
.\" García <gerardo@cica.es>
.\"
.TH SETFDPRM 8 "20 Noviembre 1993" "Linux 0.99" "Manual del Programador de Linux"
.SH NOMBRE
setfdprm \- establece parámetros del disco flexible dados por el usuario
.SH SINOPSIS
.B "setfdprm [ \-p ]"
dispositivo nombre
.br
.B "setfdprm [ \-p ]"
dispositivo tamaño sectores cabezas pistas extensión hueco proporción espec1 hueco_fmt
.\" device size sectors heads tracks stretch gap rate spec1 fmt_gap
.br
.B "setfdprm [ \-c ]"
dispositivo
.br
.B "setfdprm [ \-y ]"
dispositivo
.br
.B "setfdprm [ \-n ]"
dispositivo
.SH DESCRIPCIÓN
.B setfdprm
es una utilidad que puede emplearse para cargar parámetros de disco en
los dispositivos de disco flexible auto-detectables, para borrar
antiguos conjuntos de parámetros y para deshabilitar o habilitar
mensajes de diagnósticos.

Sin ninguna opción,
.B setfdprm
carga el
.I dispositivo
(usualmente
.I /dev/fd0
o
.IR /dev/fd1 )
con un nuevo conjunto de parámetros con la
entrada
.I nombre
encontrada en
.I /etc/fdprm
(normalmente nombrada 360/360, etc.).  Estos parámetros permanecen en
efecto hasta que el disco se cambie.
.SH OPCIONES
.TP
.BI \-p " dispositivo nombre"
Carga permanentemente un nuevo conjunto de parámetros para el
dispositivo de disco flexible auto-configurable especificado para la
configuración cuyo
.I nombre
aparezca en
.IR /etc/fdprm .
Alternativamente, los parámetros pueden darse directamente en la línea
de órdenes.
.TP
.BI \-c " dispositivo"
Borra el conjunto de parámetros del dispositivo de disco flexible
auto-configurable especificado.
.TP
.BI -y " dispositivo"
Habilita mensajes de detección de formato para el dispositivo de disco flexible
auto-configurable especificado.
.TP
.BI -n " dispositivo"
Deshabilita mensajes de detección de formato para el dispositivo de
disco flexible auto-configurable especificado.
.SH FALLOS
Esta documentación está enormemente incompleta.
.SH FICHEROS
.I /etc/fdprm
.SH AUTOR
Werner Almesberger (almesber@nessie.cs.id.ethz.ch)
