'\" t
.\" Copyright (C) 2001 Andries Brouwer <aeb@cwi.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traducido por Miguel Pérez Ibars <mpi79470@alu.um.es> el 20-marzo-2005
.\"
.TH UNITS 7 "22 diciembre 2001" "Linux" "Manual del Programador de Linux"
.SH NOMBRE
units, kilo, kibi, mega, mebi, giga, gibi \- prefijos decimales y binarios
.SH DESCRIPCIÓN
.SS Prefijos decimales
El sistema SI de unidades usa prefijos para indicar potencias de diez.
Un kilómetro son 1000 metros, y un megavatio son 1000000 vatios.
Debajo se muestran los prefijos estándares.

.RS
.TS
l l l.
Prefijo Nombre  Valor
y	yocto	10^-24 = 0.000000000000000000000001
z	zepto	10^-21 = 0.000000000000000000001
a	atto	10^-18 = 0.000000000000000001
f	femto	10^-15 = 0.000000000000001
p	pico	10^-12 = 0.000000000001
n	nano	10^-9  = 0.000000001
u	micro	10^-6  = 0.000001
m	milli	10^-3  = 0.001
c	centi	10^-2  = 0.01
d	deci	10^-1  = 0.1
da	deka	10^ 1  = 10
h	hecto	10^ 2  = 100
k	kilo	10^ 3  = 1000
M	mega	10^ 6  = 1000000
G	giga	10^ 9  = 1000000000
T	tera	10^12  = 1000000000000
P	peta	10^15  = 1000000000000000
E	exa	10^18  = 1000000000000000000
Z	zetta	10^21  = 1000000000000000000000
Y	yotta	10^24  = 1000000000000000000000000
.TE
.RE

El símbolo para el prefijo micro es la letra griega mu, a menudo escrita
como u en un contexto ASCII donde esta letra griega no está disponible.
Véase también
.sp
.RS
http://physics.nist.gov/cuu/Units/prefixes.html
.RE
.SS Prefijos binarios
Los prefijos binarios se asemejan a los decimales, pero tienen una 'i' adicional
(y "Ki" comienza con una 'K' mayúscula). Los nombres se forman tomando
la primera sílaba de los nombres del prefijo decimal con aproximadamente el mismo
tamaño, seguida de "bi" por "binario".

.RS
.TS
l l l.
Prefijo Nombre  Valor
Ki	kibi	2^10 = 1024
Mi	mebi	2^20 = 1048576
Gi	gibi	2^30 = 1073741824
Ti	tebi	2^40 = 1099511627776
Pi	pebi	2^50 = 1125899906842624
Ei	exbi	2^60 = 1152921504606846976
.TE
.RE

Véase también
.sp
.RS
http://physics.nist.gov/cuu/Units/binary.html
.RE
.SS Debate
Antes de que se introdujeran estos prefijos binarios, era bastante
común usar k=1000 y K=1024, al igual que b=bit, B=byte.
Desafortunadamente, la letra M ya es mayúscula, y no puede ser
puesta como mayúscula de nuevo para indicar la condición de binario.

Al principio poco importaba esto, puesto que los módulos de
memoria y los discos venían en tamaños que eran potencias de dos, 
así que todo el mundo sabía que en esos contextos "kilobyte" y "megabyte"
hacían referencia a 1024 y 1048576, respectivamente. Lo que al principio
era un uso descuidado de los prefijos "kilo" y "mega" comenzó a convertirse
en "el verdadero significado" cuando se vieron implicadas las computadoras.
Pero después la tecnología de los discos cambió, y los tamaños de los discos eran
números arbitrarios.
Tras un período de incertidumbre todos los fabricantes de discos adoptaron
el estándar, a saber k=1000, M=1000k, G=1000M.

La situación era liosa: en los modems 14k4, k=1000; en los diskettes de 1.44MB
.\" also common: 14.4k modem
, M=1024000; etc. En 1998 el IEC aprobó el estándar 
que define los prefijos binarios dados arriba, permitiendo a la gente
ser precisa e inequívoca.

Así que, hoy en día, MB = 1000000B y MiB = 1048576B.

En el mundo del software libre los programas
están cambiando lentamente para ajustarse a las reglas. Cuando el núcleo
de Linux arranca y dice

.RS
.nf
hda: 120064896 sectors (61473 MB) w/2048KiB Cache
.fi
.RE


los MB son megabytes y los KiB son kibibytes.
