.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 21 Aug 1994 by Michael Chastain <mec@shell.portal.com>:
.\"   Removed note about old libc (pre-4.5.26) translating to 'sync'.
.\" Modified 15 Apr 1995 by Michael Chastain <mec@shell.portal.com>:
.\"   Added `see also' section.
.\" Modified 13 Apr 1996 by Markus Kuhn <mskuhn@cip.informatik.uni-erlangen.de>
.\"   Added remarks about fdatasync.
.\" Modified Fri Jan 31 16:27:42 1997 by Eric S. Raymond <esr@thyrsus.com>
.TH FSYNC 2 "1994-04-13" "Linux 1.3.85" "Linux Programmer's Manual"
.SH NAME
fsync \- synchronize a file's complete in-core state with that on disk
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int fsync(int " fd );
.SH DESCRIPTION
.B fsync
copies all in-core parts of a file to disk.

In some applications,
.B fdatasync
is a more efficient alternative to
.BR fsync .
.SH "RETURN VALUE"
On success, zero is returned.  On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EBADF
.I fd
is not a valid file descriptor open for writing.
.TP
.BR EROFS ", " EINVAL
.I fd
is bound to a special file which does not support synchronization.
.TP
.B EIO
An error occurred during synchronization.
.SH "CONFORMING TO"
POSIX.1b (formerly POSIX.4) 
.SH "SEE ALSO"
.BR bdflush (2),
.BR fdatasync (2),
.BR sync (2),
.BR update (8),
.BR sync (8)
