#!/bin/bash
# Script que aplica la transformación gr2img.sed a todos los archivos
# cuya extensión es sgm
# Autor: Jaime Irving Dávila, Fecha: 3-Marzo-2002
# Se cede al dominio público

ext=*.sgm
for docarch in $ext
  do
  cat $docarch | ./gr2img.sed > $docarch.sed;
  mv $docarch.sed $docarch
  done;

