#!/bin/bash
##
# Guía de Administración de Redes Linux V2.0 / GARL2
# Copyright (C) 2001,2002 Juan J. Amor / Hispalinux
# Modificado por Jaime Irving Dávila, 2002, para 

# Programa bajo la proteccion de GPL 2.0
##
# $Id: haz_dep_sgm,v 1.2 2002/02/18 02:40:06 jadavila Exp $
##

DIR_MAKEFILE=`pwd`

# Generacion de dependencias a partir de los sgm* existentes
echo -n 'DEPENDENCIAS = '  > ${DIR_MAKEFILE}/.dependencias

DEPEND=`ls *.sgm*`

echo -n $DEPEND >> ${DIR_MAKEFILE}/.dependencias

# Generación de dependencias para el índice
echo "" >> ${DIR_MAKEFILE}/.dependencias
echo -n 'DEPINDICE = '  >> ${DIR_MAKEFILE}/.dependencias
echo -n `echo $DEPEND | sed 's/index.sgml//g'` >> ${DIR_MAKEFILE}/.dependencias

# Fin de linea all:
echo "" >> ${DIR_MAKEFILE}/.dependencias
echo "" >> ${DIR_MAKEFILE}/.dependencias

