#!/bin/bash
# Script que aplica la transformación in2cm.pl a todos los archivos
# cuya extensión es sgm
# Autor: Jaime Irving Dávila, Fecha: 5-Mayo-2002
# Se cede al dominio público

ext=*.sgm
script=./in2cm.pl
for docarch in $ext
  do
  cat $docarch | $script > $docarch.sed;
  mv $docarch.sed $docarch
  done;

