#!/bin/bash
##
# Generador automatico de Dependencias de Makefile
# (C) 1999 Juan J. Amor / Hispalinux
##
# $Id: haz_dep,v 1.1.1.1 2000/07/10 17:49:07 jjamor Exp $
##

DIR_MAKEFILE=`pwd`

# Parte de los COMOs

cd ../../COMO-INSFLUG/es/html

echo -n 'htmls: ' > ${DIR_MAKEFILE}/.dependencias

for var in `ls`
do
	case $var in
	  MD5) echo "Detectado fichero inutil...";;
	  *) nombre=`basename $var .html.tgz`
	     echo -n "\$(DIR_OBJETIVOS)/$nombre/.fecha " >> ${DIR_MAKEFILE}/.dependencias;;
	esac
done

# Parte de los miniCOMOs

cd ${DIR_MAKEFILE}/../../COMO-INSFLUG/es/mini/html

echo -n 'minihtmls: ' > ${DIR_MAKEFILE}/.dependencias.mini

for var in `ls`
do
	case $var in
	  MD5) echo "Detectado fichero inutil...";;
	  *) nombre=`basename $var .html.tgz`;
	     echo -n "\$(DIR_OBJETIVOS)/$nombre/.fecha " >> ${DIR_MAKEFILE}/.dependencias.mini ;;
	esac
done

