#!/bin/bash
# mandiff: Muestra las diferencias entre dos páginas de manual
#	   El programa para este propósito es 'vimdiff' por defecto;
#	   si éste no se encuentra instalado se usa el 'diff' tradicional
#          con la opción de contexto
# Observacion: el nombre de la página no debe contener el '.seccion' del final

if [ $# -ne 2 ]
then
	echo "Uso: `basename $0` seccion pagina"
	exit 1
fi

DIFF=`which vimdiff 2>/dev/null`
if [ -z $DIFF ]
then
	PAGINADOR='| less'
fi
: ${DIFF:='diff -c'}

$DIFF man-pages-1.28/man$1/$2.$1 man-pages-1.55/man$1/$2.$1 $LESS 
exit 0
